### ISSUE TITLE
map magnitudes to dusted magnitudes in protoDC2

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#104]
It is recently discovered that the "dusted" magnitudes in the protoDC2 catalogs are accounting for the dust extinction from the host galaxy, but not from the Milky Way. Hence, these dusted magnitudes are what most general users would want to use. However, currently the magnitudes that are exposed via GCR are the undusted magnitudes, which are mostly only relevant for CatSim. 

Hence, we should map the magnitudes in GCR to dusted magnitudes in protoDC2. 

Thanks to @aphearin @evevkovacs @danielsf @rongpu for raising the clarifying this issue.

**Comment by evevkovacs** [comment]
Some catalogs may not even have "dusty" magnitudes available, so we need to accommodate this possibility and provide a way for users to know if they are being provided dusty or dust-free magnitudes. The simplest option is to modify the schema definition to allow for either possibility and have the catalog providers add a metadata category to specify which type of magnitude is provided. A variable such as "dusty" set to either True or False would work.  Other more complex options include specifying dusty or dust-free magnitudes in the schema, but this could lead to an explosion of quantities once lensing effects are included.

**Comment by yymao** [comment]
Actually, for catalogs built using empirical methods, the magnitudes usually already take host extinction into account (hence, dusty in this terminology).

**Comment by aphearin** [comment]
Brief technical side note. I think language like "host-extincted" rather than "dusty" is more clear. For example, @rongpu was presented with "dusted" vs. "undusted" colors, and he understandably assumed we were referring to Galactic extinction, not extinction within the host galaxy. Whatever we decide on our default convention, let's keep this in mind.

**Comment by dkorytov** [comment]
The SEDs for protodDC2 don't include host galaxy dust. Should we change it to include it?

**Comment by evevkovacs** [comment]
No. CatSim is expecting SEDs without host-extinction effects. CatSim does it's own estimation of dust effects using A_v and R_v. But we should clarify in the schema that the SED quantities do not include host extinction.

**Comment by yymao** [comment]
I think we should remap the SEDs as well. We will need to change the CatSim interface, but I do think we should make the GCR quantities map to ones that are most useful for general users.

**Comment by evevkovacs** [comment]
@yymao @danielsf Scott should comment. The 2 "users" that would be most interested in SEDs are CatSim for Instance-Catalog generation and the PZ WG for calibration. The former wants SEDs without host extinction and the latter with. The best option might be for the schema to provide both in this case and let the user decide.

**Comment by yymao** [comment]
CatSim ingests the quantities using a script, so it doesn't really care how long the quantity names are. I am mostly thinking of people who use notebook to explore the catalogs, and I think we want to use the shorter names for most-used quantities whenever possible.

**Comment by yymao** [comment]
@evevkovacs oh, sorry for not being very clear, I think we should still still map the SEDs that have no host extinction to GCR quantities and let CatSim use GCR quantities. So a more concrete proposal is:

```
sed_<start>_<width>: SEDs/totalLuminositiesStellar:SED_<start>_<width>:rest:dustAtlas
sed_<start>_<width>_no_host_extinction: SEDs/totalLuminositiesStellar:SED_<start>_<width>:rest
```

**Comment by evevkovacs** [comment]
Yes, that's exactly what I was trying to suggest above. Agreed!

**Comment by yymao** [comment]
Great. If @danielsf also agrees with use, @dkorytov, can you implement this in #105? 

And we'll also need to modify these two lines correspondingly: https://github.com/LSSTDESC/sims_GCRCatSimInterface/blob/master/python/desc/sims/GCRCatSimInterface/SedFitter.py#L35

**Comment by evevkovacs** [comment]
https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/SCHEMA.md will also have to be updated once we have consensus.

**Comment by danielsf** [comment]
This proposal sounds fine to me

**Comment by dkorytov** [comment]
Okay, I'll put those changes in.

**Comment by evevkovacs** [comment]
@yymao We should also update the schema.md document
