### ISSUE TITLE
InstanceCatalog reader needs to be able to handle sprinkled objects

### ISSUE THREAD

**Issue by danielsf** [LSSTDESC/gcr-catalogs#110]
The InstanceCatalog reader currently assumes that the galaxy catalog contains only galaxies and AGN.  The reader ignores AGN.  We need to

a) figure out how we want to handle AGN
b) add code to handle the fact that the sprinkler is going to be adding lensed AGN and SNe to the galaxy catalog

There is also the question of how we are going to deal with objects that are passed to PhoSim as fits image profiles, instead of SEDs.  The number of columns should not change for those rows (@jbkalmbach ?), but the meaning of the spatial parameters will change (see the "Spatial Models" section here)

https://bitbucket.org/phosim/phosim_release/wiki/Instance%20Catalog

**Comment by jbkalmbach** [comment]
Yeah, we are making sure that the number of columns does not change.

I'm not sure if this is helpful, but I do have a way of reading and parsing the sprinkled instance catalogs in this method: https://github.com/LSSTDESC/Twinkles/blob/issue/467/ic_validation/python/desc/twinkles/validate_ic.py#L18 that I am using to develop the instance catalog validation tests.

**Comment by yymao** [comment]
@jbkalmbach thanks for the script. Yes we can implement that in the GCR for the time being. But still I think it'll be great if we can make the underlying format easier to parse :)

**Comment by jbkalmbach** [comment]
@danielsf might want to say more about this, but he is working on making a way to write out the sprinkled catalog pieces separately. However, this will still necessitate an answer to his first point about handling general AGN in the catalog.

**Comment by yymao** [comment]
fixed by #113
