### ISSUE TITLE
add sign convention to shear parameters in schema

### ISSUE THREAD

**Issue by danielsf** [LSSTDESC/gcr-catalogs#112]
The schema does not list the sign convention for `shear_1` and `shear_2`.  Once we sort out what the convention in protoDC2 is here

https://github.com/LSSTDESC/gcr-catalogs/pull/111

we should document it in the schema.

**Comment by evevkovacs** [comment]
Sign conventions for protoDC2 were documented in the old google doc that described the schema.
It appears that section did not get moved to github. Here is the link to the google doc:[](https://docs.google.com/document/d/1rUsImkBkjjw82Xa_-3a8VMV6K9aYJ8mXioaRhz0JoqI/edit#)

**Comment by danielsf** [comment]
That just links me to `SCHEMA.md` in `gcr-catalogs`, which says "(sign convention to be supplied)" under `shear_1` and `shear_2`.  I am interpreting that as "sign convention not yet determined".  Am I wrong?  Does it mean "providers of catalogs should make sure to tell us what their sign convention is somewhere in the catalog"?

**Comment by evevkovacs** [comment]
@danielsf  Sorry, I should have been more clear. You have to scroll to the bottom of the google doc. Under "Discussion and Notes", you will find a section on shear sign conventions.

**Comment by danielsf** [comment]
Thanks, Eve.  Sorry I didn't see that sooner.

**Comment by yymao** [comment]
addressed in PR #111, commit b62b5e8
