### ISSUE TITLE
remove `*_any` quantities

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#13]
Currently we have quantities like `magerr_u_any`, which were introduced so that users who do not care using the exactly same quantity among different catalogs would be able to grab the quantity without worrying which quantity exists in which catalog.

Since [GCR 0.2.1](https://github.com/yymao/generic-catalog-reader/releases/tag/v0.2.1), a new (and arguable better) way to do this is to use the `first_available()` method. 

So, instead of doing:

    gc1.get_quantities(['magerr_u_any', 'magerr_g_any'])
    gc2.get_quantities(['magerr_u_any', 'magerr_g_any'])

One can now do:

    mag_u_acceptable = ['magerr_u_lsst', 'magerr_u_sdss', 'magerr_u_des']
    mag_g_acceptable = ['magerr_g_lsst', 'magerr_g_sdss', 'magerr_g_des']
    gc1.get_quantities([gc1.first_available(mag_u_acceptable), gc1.first_available(mag_g_acceptable)])
    gc2.get_quantities([gc2.first_available(mag_u_acceptable), gc2.first_available(mag_g_acceptable)])

It is true that the code in the new version would be *longer*. But it is more explicit and does not require the reader to define those `*_any` quantities. 

@j-dr @evevkovacs @dkorytov @EiffL What do you think?  Any comments/suggestions?  If that looks good I'll start to remove `*_any` quantities in the existing readers.

**Comment by evevkovacs** [comment]
I think this new method is better. It allows the user to define what the possibilities can be. Not to add more work, but I am assuming that the list of acceptable quantities is prioritized? ie above it asks for lsst first, then failing that sdss, then failing that des?

**Comment by yymao** [comment]
Yes, hence the name `first_available`. This way, the user can decide the fallback sequence they need.

**Comment by EiffL** [comment]
I like it, my only worry would be that you don't know exactly which magnitude is being used, a printed or log message would be a nice feedback to the user in case the first choice is not available.

**Comment by yymao** [comment]
@EiffL, that's a good point. The question is whether this function should always print that information out, since the user can always add a line to check? Thoughts?

**Comment by evevkovacs** [comment]
The user specifies and ordered list (that's why I asked), so by looking at 
the quantities list it is easy to see what's available. That said, a 
message would be a nice convenience.


On Mon, 6 Nov 2017, Francois Lanusse wrote:

> Date: Mon, 6 Nov 2017 13:46:36
> From: Francois Lanusse <notifications@github.com>
> Reply-To: LSSTDESC/gcr-catalogs
>     <reply+0076fc4d45fe1a28e2d6432cea33dd100714afc9cf91294d92cf0000000116187e1
>     c92a169ce1030283e@reply.github.com>
> To: LSSTDESC/gcr-catalogs <gcr-catalogs@noreply.github.com>
> Cc: Eve Kovacs <kovacs@anl.gov>, Mention <mention@noreply.github.com>
> Subject: Re: [LSSTDESC/gcr-catalogs] remove `*_any` quantities (#13)
> 
> 
> I like it, my only worry would be that you don't know exactly which magnitude is being used, a printed or log message would be a nice
> feedback to the user in case the first choice is not available.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.[AHb8TaIcXb_NsvwDtgQP7JXmXUE3AArqks5sz2IcgaJpZM4QTv7F.gif]
> 
> 
>

***************************************************************
Eve Kovacs
Argonne National Laboratory,
Room L-177, Bldg. 360, HEP
9700 S. Cass Ave.
Argonne, IL 60439 USA
Phone: (630)-252-6208
Fax:   (630)-252-5047
email: kovacs@anl.gov
***************************************************************

**Comment by EiffL** [comment]
I think a message in case the first choice is not available, something like "warning: %s not available, fallback quantity: %s". It is true that users can check, just in case they forget.

**Comment by yymao** [comment]
OK. I've added that feature to GCR https://github.com/yymao/generic-catalog-reader/commit/659cd0bf61

**Comment by yymao** [comment]
Resolved by #14
