### ISSUE TITLE
add config for HSC coadd catalogs

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#135]
@EiffL is preparing the HSC coadd catalogs that can use the same coadd reader. @EiffL will add a config file once the HSC coadd catalogs are ready. 

In the case that we need to modify the HSC coadd catalog reader slight, we can inherit the DC2 coadd reader.

**Comment by EiffL** [comment]
on it

**Comment by EiffL** [comment]
@yymao @wmwv are  you offended if the hsc catalog exposes fields named with the  lsst extension, like `mag_i_lsst` ?

**Comment by yymao** [comment]
@EiffL we are dropping `_lsst` postfix (see #132 #133). I think you can have `mag_i` and `mag_i_hsc` and let them point to the same quantity?

**Comment by EiffL** [comment]
fantastic \o/ (I will just have mag_i then)
