### ISSUE TITLE
Should we have both 'good' and 'clean' in DC2 coadd reader?

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#136]
In the DC2 coadd reader, `good` is defined as both no flagged pixels and not deblended (`deblend_skipped`).  (code snippet below).

Should we instead define `good` as no flagged pixels, and a new column `clean` = `good`& `deblend_skipped`?

```
modifiers['good'] = (
            create_basic_flag_mask,
            'deblend_skipped',
            'base_PixelFlags_flag_edge',
            'base_PixelFlags_flag_interpolatedCenter',
            'base_PixelFlags_flag_saturatedCenter',
            'base_PixelFlags_flag_crCenter',
            'base_PixelFlags_flag_bad',
            'base_PixelFlags_flag_suspectCenter',
            'base_PixelFlags_flag_clipped',
        )
```

**Comment by yymao** [comment]
Sounds good. Make it so :p

**Comment by wmwv** [comment]
@yymao I realize I meant the opposite of what I wrote in the code snippet above (and thus what got implemented).
I think we want objects that *were* `deblend_skipped` & `good` to be the additional definition of `clean`.
I.e., isolated objects that didn't have to be deblended are 'clean'.

**Comment by EiffL** [comment]
From the HSC lensing catalog paper 1705.06745 :
```
We also imposed cuts to avoid objects with problematic image
processing, including the following scenarios: extremely large
groups of objects that the deblender skipped (usually caused by
bright stars); 
```

**Comment by wmwv** [comment]
@EiffL is of course right.  I was wrong.  I am now more enlightened and the code should remain the same.

In practice, I think there were 2 objects that were `good` but not `clean` in the DC2 Run 1.1p files.
