### ISSUE TITLE
Description of all the fields in DC2 coadd reader also accesible through GCR

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/gcr-catalogs#143]
@wmwv @yymao @djperrefort  I realised that some of the fields computed at the `merge_tract_cat.py` level are not documented in `SCHEMA.md`, for  instance `mag_i` is a psf magnitude but is documented in `SCHEMA.md` because `mag_i` was already defined in the  extra catalog section. 
Link to this issue is  #142 , so I'm thinking maybe we shouldn't store the schema in a markdown file, but in something more "parsable" so that we can easily publish/access/query it from various places

**Comment by wmwv** [comment]
I agree that the documentation for the schema should be more automatically generated directly from the code.  For the next few weeks let's focus on manually updating the `SCHEMA.md`, and the re-architect after the collaboration meeting.

**Comment by wmwv** [comment]
Yes.  That would be a reasonable goal and I don't think it's that hard.  It should only be a couple of hours of work.  @djperrefort Can you take a first try at this, then discuss in person with Yao, then meet with me to review the descriptions.
