### ISSUE TITLE
Expose galaxy ellipticity in protoDC2 reader

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/gcr-catalogs#15]
The current implementation of the reader does not define an `ellipticity` field for the galaxy, nor does it define fields like `disk_re_a_true` related to galaxy morphology. The information seems to be in there (a number of morphology related native fields) but not sure how they translate into the quantities described in the schema.

**Comment by yymao** [comment]
Does anyone know why/how GitHub prevents me from assigning @dkorytov ..? 

BTW, @j-dr, how was `ellipticity` defined in the Buzzard catalog?

**Comment by j-dr** [comment]
Ellipticity (shear) is defined as being the components of ellipticity (shear) along the local RA,DEC directions.

**Comment by yymao** [comment]
Note: this is required by https://github.com/LSSTDESC/descqa/issues/14

**Comment by dkorytov** [comment]
I'll add the ellipticity along RA/Dec and expose them as GCR quantities.

**Comment by yymao** [comment]
This has been fixed already.
