### ISSUE TITLE
GCR API Notebook Feedback

### ISSUE THREAD

**Issue by djperrefort** [LSSTDESC/gcr-catalogs#163]
There has been some confusion by individuals working through the gcr-catalogs demo notebook on how to use the API. The notebook should be edited to improve clarity.

**Comment by wmwv** [comment]
@djperrefort Is there more that should be done on this issue, or should we close it?

**Comment by djperrefort** [comment]
This issue was meant to remind us about an offline conversation we had.... but I don't think anyone remembers what that conversation was about. This issue can be closed.
