### ISSUE TITLE
Could the object catalog reader generate and cache just one immutable NaN array?

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#168]
@yymao Could the object catalog reader be configured to generate just one immutable NaN array and cache that array to be returned anytime some one asked for a column that was not present but should be?

**Comment by yymao** [comment]
I guess so, but it needs to be one per patch. I'll try implementing it.

**Comment by yymao** [comment]
Under development in https://github.com/LSSTDESC/gcr-catalogs/tree/u/yymao/object-reader-cache-constant-array
