### ISSUE TITLE
Read pre-specified schema in 'dc2_coadd' if available.

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#169]
If a schema has been provided for 'dc2_coadd' then read that schema and assume that this is the schema that all data would have.

1. [x] Decide on format for file:  JSON, YAML?
2. [x] Implement reading schema
3. [x] Implement fall back if quantity not present (I think this functionality already exists).

Schema file should presumably live in the same directory as the data files.

**Comment by wmwv** [comment]
@yymao  What's your vote:
JSON
YAML?

**Comment by yymao** [comment]
YAML. 

See also [this yaml file](https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/catalog_configs/_dc2_object_meta.yaml) @djperrefort created for the quantity info. I assume we can use the same file for schema too.

**Comment by wmwv** [comment]
Very much like that file, yes.

However, I'm planning on auto-generating this file at the time of the catalog file generation and putting the YAML file in the data directory.  This makes the data a little more self-documenting.

So `native` quantities are explicitly curated and get documented in `_dc2_object_meta.yaml`, while `non_native` quantities are described alongside the data files containing those quantities.

**Comment by wmwv** [comment]
I'm thinking of making the YAML have dicts to name each of the elements.
```
ra: {'description': 'Right Ascension', 'units': 'degree'}
```

Will the gcr-catalog reader need datatype (float64, bool, etc.)?

**Comment by yymao** [comment]
Agreed with making it a dictionary. That's [what GCR wants](https://github.com/yymao/generic-catalog-reader/blob/master/GCR.py#L392), anyway. 

GCR doesn't need data type.

**Comment by djperrefort** [comment]
I also +1 for the dictionary. I suggest including entries for each of the band specific values instead of using the `<band>` placeholder we are currently relying on. Otherwise, the entire dictionary will have to be iterated over when the reader is instantiated to format each item.

**Comment by wmwv** [comment]
Reader implemented to generate column names from schema.  But it isn't really relied on yet.  It just loads the column names.

@yymao
1. Is it correct that as long as we need to read the HDF files to get the patches, there's no clear gain for already known the column names?
2. In other words, should this present issue essentially be resolved in this minor way and wait for a refactoring of the data files into tract+patch to populate the `datasets` `ObjectTableWrapper` list without having to open the HDF files?

**Comment by yymao** [comment]
@wmwv 

1. I think there will still be some gain. Right now the reader [opens all tract files to get the patches (i.e. datasets)](https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/dc2_object.py#L359), but then it still need to [read in the column list from all dataset and get a union of them](https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/dc2_object.py#L370). I suspect the second part is taking more time than the first part. 

2. But if we do plan to change the underlying data format, I see no particular reason to update the reader now rather than wait for the new underlying data format.

**Comment by yymao** [comment]
Fixed by #171
