### ISSUE TITLE
enforce md5sum check for cosmoDC2

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#184]
To ensure reproducibility, we will enforce md5sum check for the version of cosmoDC2 that will go into image simulation, similar to what we did for protoDC2.

This task includes adding md5 sum check in the cosmoDC2 reader and add the md5 sum values in the corresponding config file.

**Comment by aphearin** [comment]
I definitely agree this is a good idea. Thanks for pushing forward on this, @evevkovacs and @yymao!

**Comment by yymao** [comment]
@evevkovacs kindly estimated the time to compute the md5 sum for the full cosmoDC2 catalog will be longer than 2 hours, which is not practical for either interactive use or instance catalog generation. The code to do md5 check is already in place,  but I don't think we will actually enforce md5 check for practical reasons. As a compromise, we have implemented a file size check. While the file size check it's not fireproof, it does provide reasonable protection to the file integrity. 

This file size check has been enabled by #189. I'm closing this issue now. If we do need md5 checks in the future, we can reopen this issue (or open a new one).
