### ISSUE TITLE
fix cosmoDC2 native quantities: emissionLines and ContinuumLuminosity 

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#190]
In the current cosmoDC2 reader, we manually remove native quantities `emissionLines/*` and `*ContinuumLuminosity` ([see here](https://github.com/LSSTDESC/gcr-catalogs/blob/eab3974/GCRCatalogs/cosmodc2.py#L424)). 

@dkorytov @evevkovacs, has this been fixed in the catalog? If so, we should update the reader. If not, should we fix it before we release v1.0?

**Comment by yymao** [comment]
@dkorytov do you think this will be fixed tonight? I think it'll be fine if not though, since this shouldn't affect image simulation, right?

**Comment by dkorytov** [comment]
@yymao, I have a fix for the reader already. I want to check up on a couple related things for documentation purposes. 

As far as I understand, the these quantities aren't used in the image simulation.

**Comment by yymao** [comment]
Yep, that's fine. I think they are going ahead to use the current master for image simulation anyway, so you can fix this whenever you're free, no hurry.

**Comment by dkorytov** [comment]
Okay

**Comment by yymao** [comment]
@dkorytov just checking in to see if a fix for this issue is on the way. Thanks!

**Comment by dkorytov** [comment]
I think this [emmision_line_contiuunm_fix](/LSSTDESC/gcr-catalogs/tree/u/dkorytov/emission_line_continuum_fix) branch fixes the issue. Let me double check though.
