### ISSUE TITLE
Where does +27.0 come in _modelfit_Cmodel_flux?

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#201]
@yymao @djperrefort Where does the `27.0` come from in the definition of the magnitude for `{}_modelfit_Cmodel_flux`?

https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/dc2_object.py#L270

```
  modifiers['mag_{}_cModel'.format(band)] = (
                lambda x: -2.5 * np.log10(x) + 27.0,
                '{}_modelfit_CModel_flux'.format(band),
            )
```

**Comment by yymao** [comment]
If I recall correctly this comes from @EiffL

**Comment by wmwv** [comment]
https://github.com/lsst/meas_modelfit/blob/dc1917700912961b9f389642aaa9181f024da4a6/src/UnitSystem.cc#L65

sets the default calibration object to be 27.0 mag.

It seems like the above setting in meas_modelfit is just some default convention, but not necessarily correctly based on the actual calibrations in the calexp or coadd.

@rearmstr Does that default calibration get updated further in the processing?

**Comment by yymao** [comment]
Sounds like we should make this value an argument of [`DC2ObjectCatalog._generate_modifiers`](https://github.com/LSSTDESC/gcr-catalogs/blob/v0.9.0/GCRCatalogs/dc2_object.py#L209). For example:

```python
def _generate_modifiers(pixel_scale=0.2, cmodel_zero_point=270.0, bands='ugrizy'):
```

**Comment by wmwv** [comment]
No.  I'd rather keep this hard-coded, but documented, here.

The right way is to fix this in the merged_tract file generation in `DC2-production/scripts/merge_tract_cat.py`.  That's the part that interacts with the DM code and could do this look-up correctly and set the magnitudes correctly like it does for the regular psfFlux values.

https://github.com/LSSTDESC/DC2-production/issues/272

Will come back and update the `_generate_modifiers` after the above issue is completed.

**Comment by wmwv** [comment]
Yes, `pixel_scale`, `tract`, and `patch` should all be added to the HDF5 file metadata.

I'd like to get this done for Run 1.2p.
