### ISSUE TITLE
Create default values and dtypes in schema for DC2 Object table reader

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#202]
Currently NaN is returned for any missing column.
But that's not a valid value for int or bool columns so the dtype is wrong for these columns.

1. Go through and specify dtypes for all columns in the DC2 Object `schema.yaml`
2. Go through and identify default values for these columns.
3. Test that using this new reader generates the correct dtypes.

**Comment by yymao** [comment]
(3) involves 
- modify [`DC2ObjectCatalog._generate_columns_from_yaml`](https://github.com/LSSTDESC/gcr-catalogs/blob/v0.9.0/GCRCatalogs/dc2_object.py#L383) to ingest dtypes and default values, and store them in the instance
- modify [`ObjectTableWrapper._get_constant_array`](https://github.com/LSSTDESC/gcr-catalogs/blob/v0.9.0/GCRCatalogs/dc2_object.py#L146) to allow creation of constant arrays or custom values.

**Comment by wmwv** [comment]
Closed by #208 #209 #211.
