### ISSUE TITLE
Provide named readers for trim and full DC2 catalogs

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#204]
We provide two key products with the Object table, the full set of columns, and a restricted set of columns that are only those necessary to re-construct the DPDD columns (the "trim" catalog).

While one can trivially use a filename_pattern in the config to use one of the other, I think it will be a better user experience and make some other code (specifically the `convert_merged_tract_to_parquet.py`) more generic to use named readers, rather than a named reader plus a custom config.

Two proposals:
1. Trim catalog default
Trim: `dc2_coadd_run1.1p`
Full: `dc2_coadd_run1.1p_full`

* PRO
   - Default case is the much faster access case.  Data size is 10x less.
   - "Power" users can ask for the full.
* CON
   - Change to current default behavior.

2. Full catalog default
Trim: `dc2_coadd_run1.1p_trim`
Full: `dc2_coadd_run1.1p`
* PRO
  - Users expect that they're getting a restricted set in the name.
* CON
   - Default will be much slower performance.

Question:
1. "_full" and "_trim" might be ambiguous.  They refer here to a subsample of the _columns_, but the user might expect them that they refer to the _rows_  (i.e., a subsample of objects).  Suggestions for better names welcome.

Notes:
1. As a minor implementation detail, by trim catalog I refer to the trim `table` format HDF file.  While the performance in the `table` format is slightly slower than the `fixed` format, the `table` HDF format can be read by Dask.

**Comment by yymao** [comment]
My vote would be 
- Do nothing for 1.1p
- Use Trim catalog default for 1.2p/i

**Comment by yymao** [comment]
Closed by #220. However, see #223 for a related issue.
