### ISSUE TITLE
Add flags for modelfit columns.

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#205]
1. Add the flag values in the modelfit columns to the non-native quantities.
Do this by adding entires in the `_generate_modifiers` code.
2. Check to see if there are other flags that should be added.

**Comment by yymao** [comment]
Is this still an open issue or should we deal with this by just including native quantities when generate the Parquet etc files?

**Comment by wmwv** [comment]
This is still open.  I would like the non-native quantity list in `dc2_object.py` to map to the DPDD columns.  Adding these flag columns will be a step in that direction.

But it's not a high priority, for the reasons you mention.

**Comment by wmwv** [comment]
Closed by #254.
