### ISSUE TITLE
missing halo mass definition in cosmoDC2 catalog/reader

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#236]
@marina-ricci pointed out that the `halo_mass_def` attribute in cosmoDC2 reader is missing. 

Indeed, the `halo_mass_def` is not defined for `CosmoDC2ParentClass` in `cosmodc2.py`. Also, the value is not set in the catalog files or the config files. 

@dkorytov what's the halo mass definition? I imagine it's a lot of trouble to put this into the data files, but we can put it in the config and modify the reader accordingly?

**Comment by dkorytov** [comment]
It's FoF b=0.168. Hmm, I wasn't aware about the halo_mass_def. Should I just define it as a string?

**Comment by yymao** [comment]
Yes. That works.
