### ISSUE TITLE
Reminder: Include flux density in microJy in the final catalogs

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/gcr-catalogs#243]
@egawiser among others asked us to include flux densities in microJy in this issue: https://github.com/LSSTDESC/DC2-production/issues/43

I am just capturing this here as a reminder. I believe that it will be a matter of making visible the relevant columns in the main schema or include a quantity modifier.

**Comment by yymao** [comment]
@fjaviersanchez this is for the object catalogs, right?

**Comment by fjaviersanchez** [comment]
yes!

**Comment by wmwv** [comment]
This should be implemented as a quantity modifier for `psFlux*` and `cModelFlux*` (#254).  From https://github.com/LSSTDESC/DC2-production/issues/43

> The current psFlux_* values in the Object tables as published for Run 1.1p, 1.2p, and 1.2i can easily be converted to nJy by multiplying by 57.54 (= 10^(4.4/2.5) = 10^((22.5+8.90-27)/2.5))).

**Comment by yymao** [comment]
Closed by #265.
