### ISSUE TITLE
Add catalog configs for Run 1.2i for reprocessing

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#246]
1. Rename prototype reprocessing as "_alpha"
2. Move new reprocessing as the default.
3. Check pixel scale.  Should it now be 0.2 arcsec/pix?

**Comment by wmwv** [comment]
I defined these as 'object_catalog_alpha' and 'object_catalog_new'.
The previous catalog is defined as being in 'object_catalog'.

The file directory symlink 'object_catalog' currently points to 'object_catalog_alpha'.  Once this present branch is merged, tagged, and installed as the default on NERSC we can switch the symlink.

**Comment by yymao** [comment]
Closed by #248
