### ISSUE TITLE
Add catalog configs for Run 1.2p reprocessing

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#256]
- [x] Rename previous reprocessing as `dc2_object_run1.2p_v3`
- [x] New reprocessing as `dc2_object_run1.2p_v4`
- [x] Move new reprocessing as the default `dc2_object_run1.2p`
- [x] Check pixel scale. Should it now be 0.2 arcsec/pix?

**Comment by yymao** [comment]
fixed by #257
