### ISSUE TITLE
Include hash sum in config files to ensure file version/integrity

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#26]
We can add a hash sum to the yaml config for corresponding catalog files, and let the reader check the hash sum before it loads the catalog. In this fashion we can ensure the version and integrity of the catalog files. 

The downside is that for large catalogs, it will take a long time to check hash sum (and we probably want to use Python build-in module to reduce dependency). I guess we can make checking hash sum optional in the reader? 

@evevkovacs @dkorytov @j-dr Comments/suggestions welcome.

**Comment by dkorytov** [comment]
I've added a major and minor version number in the most recent catalog and there is also a catalog creation date string. That can be used to ensure the correct version of the catalog is being read in. 

For ensuring against corruption: One way would be to have a global hash on the entire file as an option, but as Yao said that would take a long time. We can also hash each column and save it as column info quantity, just like the units string and the description string. As an option, when a data column is read in,  it's hashed and checked against the expected value. This should be quite a bit faster than hashing the entire file.

**Comment by yymao** [comment]
The version checking part is addressed in #31. Checking for file integrity is computationally expensive so I don't think we'll do it now. I'm closing this issue. If at a later time we want to check file integrity, we will open a new issue.
