### ISSUE TITLE
Update `blendedness` in DC2 Object Catalogs Run 1.2p v4 and Run 1.2i

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#262]
Change `blendedness` to be `base_Blendedness_abs_flux` for Run 1.2p v4 and Run 1.2i
But future versions (w_2018_42 and beyond) will have this defined as `base_Blendedness_abs`

The blendedness in the DC2 Object Catalog Run 1.2p v4 and Run 1.2i have their blendedness variables suffixed with `_flux` instead of `_instFlux`.  This means there's an inconsistency between suffixes for the flux values and the blendedness value.

This inconsistency is because in fact `base_Blendedness_raw_flux` is not a flux, but is rather the blendedness fraction as measure on the pixels.  See
https://jira.lsstcorp.org/browse/DM-16070
for some discussion that arose the conects of updating the blendedness values to the `instFlux` convention.

### Note
This isn't necessary to understand for this ticket, but you'll likely be curious:
`base_Blendedness_raw_*` are the quantities measure on the pixels (which aren't really 'raw' -- this is a coadd, after all)
`base_Blendedness_abs_*` are the quantities measured on the absolute values of the pixels (with a correction factor to account for the bias due to this)
See Bosch et al., 2018, PASJ, 70, S5, Section 4.9.11 for details.

**Comment by yymao** [comment]
@wmwv thanks for opening this issue. We can deal with this like how we dealt with `_flux`/`_instFlux`, and that's probably the way to go for the short term. But I am wondering if there is a way to implement some kind of automatic check (at the reader level), instead of setting more version flags.

**Comment by wmwv** [comment]
I've managed to get myself all confused.  For now, the matching with `_flux` and `_instFlux` matches that of the true flux fields and everything is correct.

In the future, when `blendedness` should be matched to just `base_Blendedness_abs`, we'll have to revisit this.
