### ISSUE TITLE
Create an emulated transient+variable catalog based on the truth catalog

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#269]
Create an emulated transient+variable catalog that
a) Includes errors
b) And thus it provides exactly the same API as the "real" simulated DC2 data will provide.

**Comment by yymao** [comment]
cc @rbiswas4 @reneehlozek so that this thread is on their radar.

**Comment by wmwv** [comment]
@yymao My plan is that this adds columns providing the values that will be in the full DIA catalogs.  Should I 
1. Create a subclass of `DC2TruthCatalogLightCurveReader` that adds columns?
2. Create a new class `DC2TEmulatedCatalogLightCurveReader` that redoes everything in the truth catalog and does not include truth.
3. Create a composite catalog where the values in the emulated catalog are dependent on values in the truth catalog?
4. Some other way?

**Comment by yymao** [comment]
I am inclined to (2).

**Comment by yymao** [comment]
@wmwv is this still needed now that we are generating a _true_ truth catalog?

**Comment by yymao** [comment]
Closing this since we do have _real_ DIA catalogs. @wmwv please feel free to reopen if needed.
