### ISSUE TITLE
Make gcr-catalogs more easily installable outside NERSC

### ISSUE THREAD

**Issue by boutigny** [LSSTDESC/gcr-catalogs#271]
Deploying `gcr_catalogs` outside NERSC is complicated and error prone because the location of the catalogs are hardwired in the configuration files. I would suggest to implement a mechanism to record  in a single place the path name of the  root directory where all the  the catalogs are stored.
For instance at IN2P3, the catalogs are all stored in the root directory: `/sps/lsst/data/desc/catalogs`. If we could have a similar unique catalog top directory at NERSC and record the corresponding path name in a single configuration file, everything could be deployed everywhere very easily.

The complication is that catalogs are located in several places at NERSC.

**Comment by yymao** [comment]
Adding an installation option or a config with root directory is not difficult, but as @boutigny pointed out, the complication is that catalogs are located in several places at NERSC. (In fact, if all catalogs are under the same root directory, a simple "replace all" in the catalog yamls would do.)

So I think we need to involve @heather999 in this conversation.

**Comment by boutigny** [comment]
I would really prefer to have the path name of the root directory stored in a config file rather than having to do a "replace all"

**Comment by JulienPeloton** [comment]
> [#271] For instance at IN2P3, the catalogs are all stored in the root directory: /sps/lsst/data/desc/catalogs
How difficult/realistic would it be to do the same at NERSC (i.e. store all the catalogs under the same root)?

**Comment by yymao** [comment]
That's a question I am hoping @heather999 can help answer!

**Comment by heather999** [comment]
Sorry, I see I missed this issue until now!
My understanding is that the catalogs at NERSC are located in a variety for directories under `projecta`, but we could set up a common `/global/projecta/projectdirs/lsst/production/catalogs` and create symlinks pointing to all of the catalogs.  If we can achieve agreement, we might be able to move all of the catalogs into that one directory - but that will take a wider discussion.
Please excuse my ignorance - but where are the paths to the catalogs set up now in this repo?

**Comment by boutigny** [comment]
They are in individual files in `GCRCatalogs/catalog_configs`

**Comment by yymao** [comment]
If we use the symlink solution, would copying from symlink location to IN2P3 works, or does the copying still need to use the original paths?

**Comment by boutigny** [comment]
Ideally we could have a different "root path" at NERSC (/global/projecta/projectdirs/lsst/production)  and at IN2P3 ( /sps/lsst/data/desc), this root path being stored in a configuration file specific to the site. Then we could have the same naming convention for the catalogs, possibly using a complex directory tree structure. These paths would be stored in `GCRCatalogs/catalog_configs` and would be common to all the sites. Then, sites would be free to create links or to store the files directly at the defined locations

**Comment by yymao** [comment]
Right, but there could be non-catalog files under the same root directory, so how should we only select catalog files when copying?

**Comment by boutigny** [comment]
IMHO there should be only catalog files under the root directory. So at NERSC the root directory would be: `/global/projecta/projectdirs/lsst/production/catalogs`

**Comment by yymao** [comment]
Right, so my question is that, for NERSC, should we (a) move the actual catalog files to `/global/projecta/projectdirs/lsst/production/catalogs`, OR (b) make symlinks under `/global/projecta/projectdirs/lsst/production/catalogs` for all catalog files (and the actual files will be still sitting somewhere else.

I believe Heather is suggesting (b), and for (b) I wonder if the transfer to IN2P3 would work as expected (i.e., would the transfer knows to copy not just the symlinks but the actual files)?

**Comment by boutigny** [comment]
I just asked to @airnandez who confirms that his transfer tools is correctly following symlinks. So (b) is fine.

**Comment by heather999** [comment]
I can definitely help with this - I just need a complete list of what catalogs I need to symlink under `/global/projecta/projectdirs/lsst/production/catalogs`.  My current idea is to go over all the contents of the yaml files, but if there a simpler way to get that list, I'd be happy to hear it!

**Comment by yymao** [comment]
@heather999 maybe the first thing (that I should do) is to go through the configs and homogenize the keyword used for base directory. Many use `base_dir` but some use something different. Then we can do the symlink, and finally update the register and `setup.py`. 

I'll open a few issues to capture these tasks.

**Comment by yymao** [comment]
This has now been resolved with the release of v0.17.0
