### ISSUE TITLE
Create a reader for Source Table

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#274]
Create a reader for Source Table in coordination with 

https://github.com/LSSTDESC/DC2-production/issues/326

**Comment by yymao** [comment]
Is the plan to duplicate the data and save to flat files (i.e., like what we did with the object catalog), or to interface GCRCatalogs with butler directly?

**Comment by jiwoncpark** [comment]
Hi @wmwv! As we discussed on the Berkeley Hack Day, I'm happy to be the reviewer, but please let me know if I can be of earlier help as well.

**Comment by yymao** [comment]
Fixed by #277.
