### ISSUE TITLE
Create a reader for Forced Source Table

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#279]
Create a reader for the Forced Source Table of the LSST Data Products Definition Document ( ls.st/dpdd).  This is Table 4.3.3 of the 2018-02-19 version of the document.  Just 7 columns:

```
objectId
ccdVisitId
psFlux
psFluxErr
psDiffFlux
psDiffFluxErr
flags
```

Note that if difference imaging has been performed, then this table provides both the regular image forced photometry and the difference-image forced photometry.  For now we will just consider the regular image forced photometry.

**Comment by yymao** [comment]
Done by #289
