### ISSUE TITLE
bug in `SingleVisitCatalog`

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/gcr-catalogs#281]
Right now if SingleVisitCatalog finds an object with negative flux, it throws an exception and breaks when trying to calculate the magnitude. This is the default behavior of the pipeline unless this line: `calib.setThrowOnNegativeFlux(False)` is added. I'm opening this issue and a related PR to prevent this from happening.

**Comment by jchiang87** [comment]
Just a heads up:  As of `w.2019.14`, the `Calib` object has been replaced by `PhotoCalib`, with interface and behavior changes related to magnitude calculations and negative fluxes.  See https://community.lsst.org/t/photocalib-has-replaced-calib-welcoming-our-nanojansky-overlords/3648

**Comment by yymao** [comment]
Thanks @jchiang87. We probably should open another issue to remind ourselves to make the `Calib` -> `PhotoCalib` before `desc-stack` is going be updated to the newer build (cc @heather999).

**Comment by heather999** [comment]
Ok - let me know when it's ready.  Be aware that I'm out on vacation next week (Apr 22 - Apr26).

**Comment by yymao** [comment]
Fixed by #282
