### ISSUE TITLE
Replace `Calib` with `PhotoCalib` in `SingleVisitCatalog`

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#283]
As Jim mentioned in #281, we will need to replace `Calib` with `PhotoCalib` in `SingleVisitCatalog` because at some point as `Calib` will be deprecated (see https://community.lsst.org/t/photocalib-has-replaced-calib-welcoming-our-nanojansky-overlords/3648).

**Comment by yymao** [comment]
Hi @fjaviersanchez, as @heather999 mentioned in #327, the `desc-stack` kernel is moving onto `w_2019_19` and `SingleVisitCatalog` will no longer work without the change `Calib` -> `PhotoCalib`.

Can you help update the reader? Thanks.

**Comment by yymao** [comment]
Yes (I don't think there's any existing PRs on this anyway).

**Comment by fjaviersanchez** [comment]
Closed by #328
