### ISSUE TITLE
What is the way of filtering quantities on a list?

### ISSUE THREAD

**Issue by rbiswas4** [LSSTDESC/gcr-catalogs#288]
I would like to select objects from DC2 whose ids match those in a list. This is mostly to find a set of galaxies that I have listed before. So, in this case, the quantity would be `galaxy_id`
I normally do this kind of check on other systems by querying 
`galaxy_id  in (0, 1, 2, 3, 4)` where the query would return objects that have `galaxy_id` matching one of the quantities in the sequence (0, 1, 2, 3, 4). 
I set up a  toy example to clarify what I am trying here: https://nbviewer.jupyter.org/26f9b1b9bcd6910ca1b60017c23bb8fc

This syntax does not seem to work on `gcr-catalogs`. Is there a different syntax for doing this?

**Comment by yymao** [comment]
Yes, there is a different syntax. For string queries, `GCRCatalogs` only supports simple operations. For more complex operations, the filter should be specified by a tuple: `(function, column_name1, column_name2, ...)`, where `function` should take numpy array(s) as inputs, and return a boolean array as the mask. This allows users to write arbitrary queries. 

Hence, in your case, the filter can be written as:
```python
filters=[(lambda x: np.in1d(x, [0, 1, 2, 3, 4]), 'galaxy_id')]
```

You can combine complex filters with string filters too:
```python
filters=['mag_r < 20', (lambda x: np.in1d(x, [0, 1, 2, 3, 4]), 'galaxy_id')]
```

**Comment by rbiswas4** [comment]
OK Thanks! This is great. Might be good as one of the things in the https://github.com/LSSTDESC/gcr-catalogs/blob/master/examples/GCRCatalogs%20Demo.ipynb . If you want you can assign me, (but I might not do it urgently)

**Comment by yymao** [comment]
@rbiswas4 It would be great if you can help with updating the demo notebook to make it more user friendly. This particular usage is indeed mentioned in `In [24]` of that notebook but probably not in a very user friendly way.

**Comment by yymao** [comment]
@rbiswas4 I think this question has been answered and will now close this issue. Feel free to reopen if you have remaining questions about the usage of `filters`
