### ISSUE TITLE
yaml.load deprecation warning

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/gcr-catalogs#298]
With the most recent versions of pyyaml, the plain `yaml.load()` is deprecated without additional options concerning safety, leading to this warning when importing the library:

```
> python -c 'import GCRCatalogs'
/global/cscratch1/sd/zuntz/env1/lib/python3.7/site-packages/GCRCatalogs/register.py:23: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
```

The seven `yaml.load`s in gcr-catalogs should be replaced with either `yaml.safe_load`, or `yaml.full_load` if we expect configuration files to contain anything beyond the most basic structures (i.e. anything that needs pickling).  I would guess that the former would make more sense here.

There is more info here: https://msg.pyyaml.org/load

**Comment by yymao** [comment]
Thanks for bringing this up @joezuntz. I am fixing this in #299.
