### ISSUE TITLE
Parallel Reading

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/gcr-catalogs#307]
Many things that we do with GCR catalog are inherently parallel, and later stages are often run with MPI.  But the initial stages where we read the catalogs are currently only serial access.  Right now that's a bottleneck, since it requires a long job at NERSC which tends to queue for ages.

Enabling parallel access to the catalogs, even if it was not very flexible, would be extremely useful.

For example, something vaguely like this would be very useful (not an attempt to use actual GCR methods):

```
def get_quantities_iter_parallel(quantities, rank=0, size=1):
    ...
    start = 0
    for i, file in enumerate(self._file_list):
        n = self.get_file_length(file)
        end = start + n
        if i % size == rank:
            data = self.load_file(file, quantities)
            yield start, end, data
        start = end
```

I don't see a simple way to make this work if filters are specified (since then you have to load all the data to find out the lengths of the output), so that could not be an option.  I'm also not suggesting thinking about parallel writing, since that's much harder.

**Comment by yymao** [comment]
@joezuntz thanks for the suggestion. I want to check if the returned information `start` and `end` in your code example are really needed. For most data formats that GCR is interfacing, getting the length (number of rows) still requires loading the whole data file. Hence, requiring `start` and `end` means each thread still needs to load all data files. 

If `start` and `end`  are not needed, then it seems to me your request can be archived by a convenience function that would very simple to implement in the base class:

```python
def get_quantities_iter_parallel(self, rank=0, size=1, **kwargs):
	it = self.get_quantities(**kwargs)
	yield from itertools.islice(it, rank, None, size)
```

Let me know!

**Comment by joezuntz** [comment]
@yymao thanks.  In my case at least the `start` and `end` values are needed, because the model is load->process->parallel-write, and to know where to write the data in the third step we need the indices to put it in.  

Although actually now I think about this more carefully the model I had imagined for doing this would not work, because we also want to filter the selection, and then the start and end positions depended on the previous values.

So while this still might be useful in general I realise it wouldn't solve the problems I have right now.  So given the demands on your time I'm happy to close!

(Side point - the code you wrote above would not help, since it still evaluates the next iterable before discarding it, and that would mean loading the data in each process)

**Comment by joezuntz** [comment]
Actually I just had a thought - one could synchronize the ranks after each reader had read their first chunk, then their second, then their third, etc.  That would be a nice solution that wouldn't require the start and end values (since we would be calculating them anyway).  It would be slightly slower than fully parallel, but still a great improvement.

My note about the function you suggested above still stands, though.

**Comment by joezuntz** [comment]
I could have a go at this if useful?

**Comment by yymao** [comment]
Sure. I am trying to figure out if this is something that we can implement in the [base class](https://github.com/yymao/generic-catalog-reader/blob/master/GCR/base.py) or that we have to implement reader by reader. 

Do you want to describe briefly your implementation plan before working on it?

**Comment by joezuntz** [comment]
From what I can tell `_iter_native_dataset` needs to be modified to accept rank and size arguments, since that's where the loop is done over datasets and the loading is integrated into it.

The shortest way I can see that would avoid having to modify all the subclasses (including some which don't easily support it) would be:
- add a class attribute on the parent `supports_parallel_read=False`
- for each subclass that we want to implement this for (the DC2 ones, for now):
-- override this attribute with `supports_parallel_read=True`
-- add `rank=0, size=1` to the iter_native_dataset implementation, and use them to only load a subset of the files by checking at each loop iteration before loading whether this rank is responsible.
- in the parent class, modify `get_quantities_iter` and `get_quantities_iter` to check if the rank and size parameters are set and whether  `self.supports_parallel_read` is True, passing `rank` and `size` along if needed, raising an error if you try to set parallel read a non-supported catalog.

How does that sound??

**Comment by yymao** [comment]
I am hesitant about overloading methods in the base class with different call signatures. But for now I don't have smarter ways if we want to implement this feature in the base class. 

However, before doing so, I wonder if a totally different approach would work: If each thread will only use certain chunks of the catalog, wouldn't it be easier to just initialize the reader with those chunks?

For example, for cosmoDC2:

```python
cat = GCRCatalogs.load_catalog('cosmoDC2_v1.1.4_small', {'healpix_pixels': [...]})
```
where `[...]` would be a list of healpixel IDs that are set differently for each thread, depending on rank and size. 

For DC2 DPDD-like catalogs, it would be

```python
cat = GCRCatalogs.load_catalog('dc2_object_run1.2i', {'filename_pattern': r'...'})
```
where r'...'  would also be a regular expression to filter the chunks needed for each thread, depending on rank and size.

**Comment by joezuntz** [comment]
That's very clever, and much better, yes!

I might even just load the full catalog in once and then examine the list of files / pixels it contains and then split them up automatically.

I'll give this a go and report back.

**Comment by yymao** [comment]
@joezuntz, I am closing this now since the issue by itself is resolved, but feel free to reopen it or open another one if you still encounter issues. I am also very interested in hearing back from you about your experience with parallel access!
