### ISSUE TITLE
potential issue with units of RA/DEC

### ISSUE THREAD

**Issue by chihway** [LSSTDESC/gcr-catalogs#33]
In protoDC2 catalog, the RA/DEC ranges seem to be from -0.00069444231 to 0.00069444231, possibly some unit issue?

This is what I did:
gc = GCRCatalogs.load_catalog('protoDC2')
catalog = gc.get_quantities(['ra', 'dec', 'shear_1', 'shear_2', 'convergence'])
catalog['ra'].min()

-0.00069444231

**Comment by yymao** [comment]
Confirmed. Issue with `majorVersion` and `minorVersion` not set correctly in the catalog. @dkorytov is working on a fix.
