### ISSUE TITLE
Create Run 2.1i Object Table catalog config/reader for 'drb1 '

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#330]
DR1b has been kindly prepared by @johannct  and transferred to NERSC by @airnandez 
https://github.com/LSSTDESC/ImageProcessingPipelines/issues/86#issuecomment-504722527

We can and should quickly make a catalog config for it and make it available through GCR.
/global/projecta/projectdirs/lsst/global/in2p3/Run2.1i/w_2019_19-v1/dpdd/calexp-v1:coadd-dr1b-v1/object_table_summary

**Comment by heather999** [comment]
@wmwv  @yymao I'd like to continue using the paths we moved to in #301, so instead we would point to `/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1i/dpdd/calexp-v1:coadd-dr1b-v1`

**Comment by wmwv** [comment]
Are you copying those over right now?

**Comment by wmwv** [comment]
Thanks, @heather999 , for catching the paths issue and copying the data into the right place.
