### ISSUE TITLE
clarify flavor of photometry in object catalogs

### ISSUE THREAD

**Issue by rmandelb** [LSSTDESC/gcr-catalogs#331]
It would be beneficial to document in some easily-findable place (schema or possibly elsewhere?) what type of photometry is recorded in the object catalogs: forced photometry from the forced source table versus non-forced photometry from the meas table.

**Comment by yymao** [comment]
@rmandelb sorry to suddenly get back to your almost-one-year-old question but isn't object catalog _by construction_ using forced photometry?

**Comment by rmandelb** [comment]
I can give you an answer based on what I vaguely recall my concern being from a year ago, but I don't know if the reasons behind it still apply.   At that time, I believe I was considering the perspective of a newbie to DC2 products (thinking ahead to the collaboration meeting and potential new users) seeing there were many different types of catalogs here and in the tutorials, and wanting to understand their key properties:

The object catalog uses forced photometry, and my question was whether this was indicated in some reasonable place in this repo.  If somebody doesn't know that's definitionally true for an object catalog (since we refer to "object catalogs" in many places and of course we are not going to give the definition each time), they could have this question given that it is possible _in principle_ to make a catalog with non-forced photometry.

This was not a suggestion that we make any kind of major changes -- just that in the few key places where users may start to interact with / learn about these files (which I was thinking could happen on confluence, in the GCR catalog list or schema, and the tutorials), they should get an indication of the flavor of the photometry, enough that they could understand how it may be used.  Again, I could be misremembering or our documentation may have changed in the past year, or maybe the GCR repo is simply not an important place to do this, so I understand if you prefer to close this issue.

**Comment by yymao** [comment]
Thanks for the clarification, @rmandelb. I agree that we use the term "Object Catalog" as a jargon, and it may not be obvious to new users what it means. 

I added a one-line description of Object Catalogs in #449 ([quick link to the rendered version](https://github.com/LSSTDESC/gcr-catalogs/blob/u/yymao/update-schema-md/GCRCatalogs/SCHEMA.md#schema-for-dc2-object-catalogs)). Would this alleviate your concern?

**Comment by rmandelb** [comment]
That would be a reasonable way to do it, though I'm not sure whether the schema or the README is the right place to do the job.  

Going back to my original question, I think it's valuable to give some indication (again in ~a sentence) which quantities are measured in a consistent way across bands versus completely independently.

**Comment by yymao** [comment]
Ah sorry, I think I totally misunderstood your original question. I thought it was about per image vs. coadd, but it's actually about fixed positions (forced photometry) vs. independent positions in individual bands. 

How about adding this sentence to the schema?

_The photometry in the Object Catalog is measured with the forced photometry method, i.e., it is consistently measured across multiple bands using a fixed position, which is determined from the reference filter for each source (the filter that best measures the source)._

**Comment by rmandelb** [comment]
Yes, that's what my question was about.  Thanks.   I understood this is taken as a given by people familiar with these products, but I couldn't find it written down in places that are commonly accessed by new users of these products.

**Comment by yymao** [comment]
Thanks, @rmandelb. Edit pushed to #449.

**Comment by yymao** [comment]
Fixed by #449
