### ISSUE TITLE
Homogenize the config keyword that indicates file location

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#345]
In an effort to make `gcr-catalogs` more easily installable outside NERSC (#271), we need to allow the root directory of file location to be configurable. The first step is to homogenize the config keyword that indicates file location. 

Proposal: 

Each catalog config that uses on-disk files must use `base_dir` to indicate the file location. Additional custom keywords can be used to indicate file names or file name patterns, but the catalog shall not access any file that does not sit in `base_dir` or its subdirectories.

**Comment by wmwv** [comment]
I agree with the spirit of this.  Which catalog configs currently don't obey this proposal?

But I would like this to be a requirement for the catalog config files themselves, but not for the general behavior of specifying custom things in `config_overwrite` arguments when loading the catalog.

**Comment by yymao** [comment]
Superseded by #448
