### ISSUE TITLE
Speed of __len__ for DC2DMCatalog and composite metacal

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/gcr-catalogs#348]
As noted here https://github.com/yymao/generic-catalog-reader/issues/26 reading the length of these catalogs is very slow.  Caching their lengths would make sense.

**Comment by EiffL** [comment]
I would add, even just opening the object catalog is taking several minutes...

**Comment by yymao** [comment]
@EiffL can you open another issue for the loading speed? It has a very different nature from this one. Thanks.
