### ISSUE TITLE
include sky area as basic mock property

### ISSUE THREAD

**Issue by duncandc** [LSSTDESC/gcr-catalogs#35]
I think we should consider including the angular area of mocks as a basic property that mock creators need to supply for their associated readers.  Are the any objections or issues I am not noticing?

**Comment by dkorytov** [comment]
I guess it should be added to the metadata section in the catalog. Does the GCR support access to the metadata section? OR do users need to access the file directly?

**Comment by yymao** [comment]
@dkorytov it should go through the reader, i.e., the reader should set `self.sky_area` to some value. The reader can set this by reading the value in the metadata of the file.

**Comment by j-dr** [comment]
@yymao, do we want this in square degrees, or square arcminutes or something else?

**Comment by yymao** [comment]
@j-dr we haven't agreed on the standard yet. Since ra and dec are in degree, it seems sq. deg. make sense?

**Comment by duncandc** [comment]
I like sq. degrees.

**Comment by j-dr** [comment]
Makes sense to me.

**Comment by dkorytov** [comment]
Yeah, I agree.

**Comment by yymao** [comment]
The Buzzard part has been addressed in #37 by @j-dr.

**Comment by yymao** [comment]
Sky area is added to DC1 in #42, and to protoDC2 in #40. We now close this issue.
