### ISSUE TITLE
Memory leak in dc2_object_run2.1i_dr1a_with_metacal_griz

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/gcr-catalogs#355]
I see a memory leak when iterating through the above catalog, which shows up for me in practice when using lots of columns.  The attached script (I had to change the ending to .txt to upload) demonstrates this using the psutil library, which reports memory usage.  The memory usage keeps increasing throughout the iteration.

The same thing also happens with dr1b in Francois' branch.

[gcr_mem_leak.txt](https://github.com/LSSTDESC/gcr-catalogs/files/3400755/gcr_mem_leak.txt)

**Comment by yymao** [comment]
**Solution for now**: turning off cache

```python
import GCRCatalogs 
cat = GCRCatalogs.load_catalog("dc2_object_run2.1i_dr1a_with_metacal_griz")
cat.master.use_cache = False
```

I'll also submit a PR to make this the default behavior. 

**Explanation**: This is not a memory leak. The HDF5 format used in the object catalog takes time to load so the reader stores cache, which increases load speed when the same file is accessed the second time, but also increases memory usage. 

**Future plan**: We are moving away from this HDF5 format and will use parquet for object catalogs, which will resolve this issue and other slow performance naturally.
