### ISSUE TITLE
Check that Run 2.1i Object Table `cmodelFlux_flag` is correctly translated from DM original file.

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#362]
@erykoff reports:

> There are a small number of objects in the `dc2_object_run2.1i_dr1` catalog that have (for example) `cModelFlux_g == 0` and `cModelFluxErr_g == 'nan'`, that are set to `cModelFlux_flag_g == False`.

Within `gcr-catalogs` we should check to make sure that we are translating the flag values correctly.

If so, then this issue is arising at the DM Science Pipelines level and we should investigate there.

**Comment by yymao** [comment]
In the reader `cModelFlux_flag_g` just simply maps to `g_modelfit_CModel_flag`, which is a column from DM pipeline I believe.

**Comment by wmwv** [comment]
Agreed.  Thanks for checking.
Problem is at DM Science Pipelines level.
Closing.
