### ISSUE TITLE
Add magnitude calculation to quantity modifier of `DC2ObjectParquetCatalog`

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#369]
With the new script introduced in https://github.com/LSSTDESC/DC2-production/pull/358, we need to add magnitude calculation to the quantity modifiers in `DC2ObjectParquetCatalog` as the magnitudes would no long exist as native quantities.

**Comment by wmwv** [comment]
@yymao I'd like to take this opportunity to just remove all of the `dm_schema_version` and `has_model_mag` awkwardness when writing the `_generate_modifiers` for `DC2ObjectParquetCatalog`.

Do this sound reasonable to you?

This requires that we agree that we will only directly generate these (non-DPDD) Parquet files for Run 2.1i and future.

Life is never easy, so maybe someday we have to put in some more version checks, but I'd really like to deprecate some of this stuff for now.  It makes the code confusing to read and particular to try to trace through calibration and zeropoints.

**Comment by yymao** [comment]
That sounds fine. But then we need to regenerate the parquet files for DR1a, 1b, and 4.

**Comment by wmwv** [comment]
Updated `DC2ObjectParquetCatalog` now reads and calculations magnitudes correctly for latest set of object catalog generated for Run 2.1.1i.

I'm now adding '{band}_FLUXMAG0' columns to the previous dr1a, dr1b, and dr4b objects in my SCRATCH.  I will verify and then copy over new files, putting previous files in an attic folder to delete in a few weeks.

The current processing references things to a reference zp of 27 mag, so FLUXMAG0 is just one number and the same for all rows.  In the Parquet format this is recognized that all entries in a column are the same, and then additional data storage is negligible.

**Comment by wmwv** [comment]
I've generated the new Parquet files for DR1a, DR1b, DR4 with the FLUXMAG0 column and tested them.  I've moved the previous versions to directories called:
`object_table_parquet_no_fluxmag0_delme_on_20191101`
and these new versions to the existing name of:
`object_table_parquet`

There is thus no change to the `catalog_configs` for these.

**Comment by heather999** [comment]
Is this all in the `/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1i/dpdd` area at NERSC?

**Comment by wmwv** [comment]
Yes.
