### ISSUE TITLE
Reader for AGN catalog

### ISSUE THREAD

**Issue by evevkovacs** [LSSTDESC/gcr-catalogs#373]
This issue tracks progress on developing a reader for the agn catalog prepared by Scott Daniel. The agn catalog contains a compilation of the galaxies that contain an agn component, along with the original magnitudes from cosmoDC2 and the magnitudes of their agn components. The final goal is to have a reader for a composite catalog comprising cosmoDC2 and the agn catalog as an add-on so that the composite catalog can be passed through DESCQA. After discussion with @yymao, we split the problem into 2 steps:
1) Reader for the agn catalog
2) Reader for the composite catalog

**Comment by evevkovacs** [comment]
With help from @yymao, the stand-alone reader for the agn-mean-mags catalog provided by Scott Daniel is complete. It has been tested in this notebook. The current implementation sums the fluxes coming from the galactic and agn components and computes the resulting magnitude, which is delivered as a schema quantity mag_*_lsst. It has also been run in DESCQA. Test results: [Color distributions without AGN contributions ] (https://portal.nersc.gov/project/lsst/descqa/v2/?run=2019-08-07_1) (note LSST filters are used in place of SDSS filters for the AGN catalog) and [Color distributions with AGN contributions](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2019-08-07_2) (Copied from comment attached to PR)

**Comment by evevkovacs** [comment]
For the composite catalog, @yymao suggested the following configuration file:
subclass_name: composite.CompositeReader
catalogs:
  - catalog_name: cosmoDC2_v1.1.4_image
    matching_method: galaxy_id
  - catalog_name: cosmoDC2_v1.1.4_agn_mean_mags
    matching_method: galaxy_id
only_use_master_attr: true

I tried this and it works, but for quantities that have the same name as those in cosmoDC2, the composite catalog delivers the quantity values from the add-on catalog as numpy masked arrays, with all rows except those appearing in the add-on catalog masked out. Since not every galaxy has an AGN, this is not what we need for DESCQA tests, for example. We need a reader whose job is to find the matching entries between cosmoDC2 and the AGN catalog and overwrite only those rows with the values from the AGN catalog. One way to do this involves subclassing the composite reader and defining suitable quantity modifiers to . Yao suggests the following code:

cat = GCRCatalogs.load_catalog('cosmoDC2_v1.1.4_image_addon_agn')

catname_dc2, catname_agn = [c['catalog_name'] for c in cat.get_catalog_info('catalogs')]

def get_composite_mag(original_mag, agn_mag):
    if np.ma.isMaskedArray(agn_mag):
        agn_mag = agn_mag.filled(fill_value=np.inf)
    m = np.minimum(original_mag, agn_mag)
    m += -2.5/np.log(10.0)*np.log1p(10**(-0.4*np.abs(original_mag-agn_mag)))
    return m
   
for band in 'ugrizy':
    cat.add_derived_quantity(
        'mag_{}_lsst_with_agn'.format(band),
        get_composite_mag,
        (catname_dc2, 'mag_{}_lsst'.format(band)),
        (catname_agn, 'mag_{}_lsst(agn)'.format(band)),
    )

**Comment by evevkovacs** [comment]
@yymao  I'm now working on part 2 of this issue, which is to produce a "combined" catalog. I have tried subclassing the CompositeCatalog class to make a reader. My goal is to produce cosmoDC2 but with the appropriate rows overwritten so that 'mag_{}_lsst' from the original cosmoDC2 includes the AGN contributions and can be used in DESCQA tests without further ado. For a start, I just wanted to read in both catalogs and add a derived quantity as you suggested above. When I try to run the code in /global/u1/k/kovacs/gcr-catalogs_agncomp/GCRCatalogs/agncombined.py on the yaml file: cosmoDC2_v1.1.4_image_combined_agn.yaml (in same path as above), I get an error:
__init__() missing 1 required positional argument: 'catalog_instances'.  I have probably messed up the subclassing, but I don't understand the structure very well. Can you please take a look and let me know what I'm doing wrong? Thanks

**Comment by yymao** [comment]
@evevkovacs The code snippet that I provided earlier was for _using_ the reader, not for developing the reader. If you want to create a new reader to add additional quantity modifiers on composition catalogs, here's how you do it:


```python
class AGNCombinedCatalog(CompositeReader):
    def _subclass_init(self, **kwargs):

        self._catalog_names = [cat.identifier for cat in self._catalogs]

        for band in 'ugriz':
            self._quantity_modifiers['mag_{}_withagn_lsst'.format(band)] = (
                get_composite_mag,
                (self._catalog_names[0], 'mag_{}_lsst'.format(band)),
                (self._catalog_names[1], 'mag_{}_lsst(agn)'.format(band)),
            )
```

I haven't got a chance to actually test the code so I can't guarantee there's no bug. Let me know if you have any questions.

**Comment by evevkovacs** [comment]
Thanks, yes I used the wrong subclass. So now I have code for the combined catalog (in /global/u1/k/kovacs/gcr-catalogs_agncomp/GCRCatalogs/agncombined.py), and am trying to overwrite the quantity names (mag_{}_lsst and mag_{}_noagn_lsst) which are also used for the composite catalog. In the code snippet above, you are defining a new quantity name, and that works. But I want to keep all the composite catalog quantity names except for the 2 above and overwrite just those with new values. Putting the overwrite in the init doesn't work. I just get back the quantities as defined in the CompositeReader class. So I'm guessing I have to define a new  _generate_quantity_modifiers to override the one defined for the CompositeReader.  But can I inherit almost all of the quantity names from the CompositeReader class without having to duplicate the code in _generate_quantity_modifiers for cosmDC2 and the AGN reader? I hope so, but don't know how.

**Comment by evevkovacs** [comment]
@yymao Added note: the above error only happens if I try to use the quantity (schema) name mag_{}_lsst. If I define a new name eg mag_{}_withagn_lsst, then the code runs just fine.

**Comment by yymao** [comment]
@evevkovacs --- the issue is actually not in the code you quoted above. I went looking at your code on NERSC, and see that the function `get_composite_mag` is returning `None` --- this is what is causing the issue: 

```python
def get_composite_mag(original_mag, agn_mag):
    if np.ma.isMaskedArray(agn_mag):
        mask = np.ma.getmask(agn_mag)
        # fill masked array and convert to ndarray
        mag_agn = agn_mag.filled(fill_value=np.inf)
        # add agn flux to original flux 
        mag_agn[~mask] = -2.5*np.log10(_calc_flux(original_mag[~mask]) + _calc_flux(agn_mag.compressed()))
        mag_agn = np.minimum(original_mag, mag_agn)
        
        return
```

In addition to the wrong return, this function seems overly complicated. It can be written as the following:


```python
def get_composite_mag(original_mag, agn_mag):
    if np.ma.isMaskedArray(agn_mag):
        agn_mag = agn_mag.filled(fill_value=np.inf)
    # add agn flux to original flux
    return -2.5*np.log10(_calc_flux(original_mag) + _calc_flux(agn_mag))
```

This should fix the issue. 

BTW, if you can push your branch to GitHub it'll make debugging much easier. I know I can see your full code on NERSC, but that is not very convenient for me and usually results in delay (like this time, sorry about that).

**Comment by evevkovacs** [comment]
Ack! I was cutting and pasting and accidentally wiped out the return argument. My apologies for taking your time with such a silly error. I'll fix it and submit a PR.

**Comment by evevkovacs** [comment]
Thanks, I have updated the code and tested it in DESCQA. I submitted PR #377. I will close this issue.
