### ISSUE TITLE
Generalize bands from dc2_object.py

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#383]
Right now the logic in dc2_object.py assumes that bands are 

#381 fixed this for the DC2ObjectParquet files.

We can fix for `DC2ObjectCatalog` as well.

Replace the two lines

```
            bands = [col[0] for col in self._schema if len(col) == 5 and col.startswith('mag_')]
```

With something that allows for multicharacter filter names.  I don't have an immediate suggestions that I'm sure can't match other things.

**Comment by yymao** [comment]
This issue actually has been fixed by #434.
