### ISSUE TITLE
Parquet DM Object catalog reader is missing some fields

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/gcr-catalogs#389]
@joezuntz pointed out that the dm object reader for the parquet files is missing the `snr_` fields, and maybe other ones as well. This is easily fixed in a couple of lines, but I wanted to raise that issue to highlight that we don't have checks that the catalogs do conform to the official schema.

**Comment by yymao** [comment]
@EiffL I think this has been fixed by #390? Can you confirm and close this?

**Comment by yymao** [comment]
@EiffL Can you confirm that this issue has been fixed by #390, and if so, close this issue? Thanks!

**Comment by yymao** [comment]
I think one of the points that you mentioned that is certainly not in #390 is a new test... but we should open a new issue for that.
