### ISSUE TITLE
catalog redshift range

### ISSUE THREAD

**Issue by chihway** [LSSTDESC/gcr-catalogs#39]
Is there a reason that the catalog is cut at z<1? Is the catalog intended to be full LSST depth?

Here's the redshift distribution (histogramming "redshift" and "redshift_true")... 

![image](https://user-images.githubusercontent.com/2736097/33590427-eabbcad2-d944-11e7-9917-4470ce634c25.png)

**Comment by yymao** [comment]
Pinging @evevkovacs @dkorytov

**Comment by evevkovacs** [comment]
Yes, protoDC2 was run on a small simulation box. We already have ~10 replications to go out to z~1. The full DC2 is based on a much larger simulation and will go out to z~2-3, with ~1 replication.
