### ISSUE TITLE
Composite Catalog return_iterator

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/gcr-catalogs#398]
It looks like when you do `get_quantities` with `return_iterator=True` on a composite catalog then GCR loads all the columns for one catalog into memory and then only really iterates on the second one.   I'm not sure if this is generally true or just for the DC2 catalogs I'm using (Parquet versions, joining the metacal and object ones).

This is okay for small catalogs but for large ones will start to cause problems with larger ones.  I'm not sure how easy this is, but there are a few ways one could avoid it.

**Comment by yymao** [comment]
What you observed is indeed the current implementation. 

The composite code does have a much more efficient mode and allows the iterator to iterate on all catalogs, but it requires that the add-on catalogs have the same row order and chunks as the base catalog. 

What we can but haven't implemented is to still use iterator on add-on when the add-on catalogs do not have the same row order but do have the same chunks as the base catalog.

**Comment by joezuntz** [comment]
Right - unfortunately in my current use case (metacal + object catalogs) they don't have the same rows, I think because some tracts failed to process in metacal.

I can see it's definitely a fiddly problem, and it's not quite our limiting factor when processing 300 deg^2, but in future it might well be, so I think worth keeping alternative solutions in mind (e.g. loading the matching column from them all, then doing the matching while keeping track of which chunk they are from.

**Comment by joezuntz** [comment]
I've hit another issue here that may be related - when you use return_iterator on a CompositeCatalog it doesn't return a masked array, just a vanilla one.

(There seems to be one exception to this - it returns a masked array for a chunk if the *entire* chunk is masked)

I assume the mask=True whenever a match is not found between the catalogs - is that right?

If so the iterator version returning unmasked data means there's no (obvious) way to filter things out.  I guess we could check for NaNs in some columns, which seems to be the fill value.

**Comment by joezuntz** [comment]
Okay, I'll open a new issue with this in.
The row ordering seems to be intrinsic to GCR, and I've made a start doing exactly what you suggest with regards to doing the looping manually.

**Comment by yymao** [comment]
@joezuntz is this issue still relevant? @EiffL told me that you are now using a metacal composite that has the exact row order and hence this should not be a problem?

**Comment by joezuntz** [comment]
It may still be a problem later, depending on catalog format, though it's less urgent now, certainly.

**Comment by joezuntz** [comment]
We could close for now and re-open later if so if you like?

**Comment by yymao** [comment]
Thanks. If it's still an (potential) issue we can keep it open.
