### ISSUE TITLE
size is missing on cosmoDC2_v1.1.4_image

### ISSUE THREAD

**Issue by plaszczy** [LSSTDESC/gcr-catalogs#399]
size_true exists but not size

**Comment by yymao** [comment]
I think ww should add some quantity modifiers for lensed sizes, @evevkovacs?

**Comment by evevkovacs** [comment]
Yes, it was assumed that users could compute this for themselves, but we can add it as a derived quantity.

**Comment by plaszczy** [comment]
rmy point is that the schema on https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/SCHEMA.md should be corrected (there are probably other missing too)

**Comment by yymao** [comment]
@plaszczy Yes, the schema file specifies the definition *if* the column exists. The schema file does not represent what quantities are available (see also https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/SCHEMA.md#L17)

**Comment by plaszczy** [comment]
@yymao that's a pity, scrolling through a web page to find the exact name of a quantity is much more convenient than running some python code. Would there be a way to indicate on the page that the quantity does not exist yet?

**Comment by plaszczy** [comment]
OK then some warning should be added to the "schema" page  with a direct link to one of your nb which describes how to get the actual list of available quantities. This would avoid misunderstandings and loss of time.

**Comment by yymao** [comment]
@plaszczy  there is a warning in the current schema file as I pointed out earlier, and it also says how to get the actual list of available quantities (see  https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/SCHEMA.md#L17)

If you have further suggestions on this warning message, it would be great if you can submit a pull request.

**Comment by plaszczy** [comment]
I guess you are referring to this part:

"Not all quantities listed below are available in all catalogs. Use list_all_quantities() to find available quantities."

you could simply move it as first item (it is more important than naming cnventions) and add a link to a notebook (for "list_all_quanties"). I don't think it deserves a PR, so if you feel it is unnecessary please close the issue.

**Comment by evevkovacs** [comment]
@plaszczy @yymao  I am happy to add a derived quantity for size to the cosmoDC2 reader if you think it would be useful, but there is a caveat. Estimating the size of a composite object (ie disk + bulge) is actually complicated eg. size_true is the luminosity weighted average of the disk and bulge sizes. An estimate for the lensed size can be obtained by computing size_true*sqrt(magnification) but it is only approximate. Our philosophy was to allow users to determine this quantity for themselves because they could best judge what level of complexity was needed for their analysis of interest.  However, if an approximate quantity is helpful, then it is easy to add it.

**Comment by plaszczy** [comment]
@evevkovacs that's ok if size is to be derived by the user, I do not need it.
@yymao My only (obvious)  point is that it took me some time to realize this page is not a list of what is available (yes people do not read always everything) and it could be beneficial to users having this important aspect highlighted. I am suggesting this for others (non-experts) and it is certainly not my role to do the work. So let's move on to more interesting stuff.
