### ISSUE TITLE
When return_iterator=True on CompositeCatalog.get_quantities does not (usually) mask its output

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/gcr-catalogs#400]
When return_iterator=False then CompositeCatalog.get_quantities returns a masked array, indicating whether it found a match.  But when return_iterator=True it returns a vanilla array unless the entire chunk is masked.

**Comment by sschmidt23** [comment]
I've seen similar behavior to this that I am trying to figure out for a composite catalog that I created.  However, I was playing with the cosmoDC2_v1.1.4_small_combined_agn catalog as an example, and I do not see a problem with that catalog (i.e. for the combined AGN catalog with return_iterator=True you *do* get the expected masked arrays and everything works as expected).  I notice for the combined AGN catalog there is a single hdf5 file for the AGN columns, so the reader is not as complex as my reader with hundreds of hdf5 files. I am wondering if it is related to the chunking of the data or some other aspect of the file ordering may be messing things up here?  Just speculation on my part.

**Comment by yymao** [comment]
I think that's the intended behavior. It returns a masked array only if needed (i.e., if mask is needed within the return chunk). See https://github.com/yymao/generic-catalog-reader/blob/master/GCR/composite.py#L233 

Hence, when using return_iterator=True, it sometimes will return vanilla array if nothing needs to be masked. The idea was that the user will check using `np.ma.is_masked`. 

This is probably not be the most user-friendly implementation TBH. But as we mentioned in #401, the composite catalog was meant for letting people use an add-on catalog quickly. It was not meant to implement a full database like python interface.

**Comment by johannct** [comment]
Perhaps make the behavior clearer in the docstring?

**Comment by joezuntz** [comment]
Either of these would make sense:
- always return a masked array
- only return the matched objects, with no mask

**Comment by johannct** [comment]
I propose to take over and learn a bit of GCR in the process. @joezuntz hopefully you'll help me soprt it out :)

**Comment by yymao** [comment]
> only return the matched objects, with no mask

Composite catalog was designed to be a left join, but I can imagine adding an option to switch to inner join. 

> always return a masked array

This can be easily done by removing this line https://github.com/yymao/generic-catalog-reader/blob/master/GCR/composite.py#L233 (and unindent the line below by 4 spaces).

**Comment by yymao** [comment]
I opened a PR in https://github.com/yymao/generic-catalog-reader/pull/29 

But I realized that this would only change the behavior of composite catalogs that use IDs to match the entries. For composite catalogs that matches the format (i.e., add-on has exactly the same row order), there's not need to mask any entry and hence still returns unmasked entries.

**Comment by evevkovacs** [comment]
@yymao @joezuntz If I understand correctly, I think this would break existing uses of the composite reader? I have several applications already that match by ID, and there are others in the works for DC2 validation that use the masking feature. I hope it will be possible to meet new needs whilst still maintaining backwards compatibility. Sorry I haven't followed in detail, but could you possibly set a flag or switch to handle the new case?

**Comment by yymao** [comment]
@evevkovacs No, this change will not break the matching mechanism. This is just to ensure that, when using matching by ID, the returned arrays are always MaskedArray. 

@joezuntz Does this PR (https://github.com/yymao/generic-catalog-reader/pull/29) address your concern? However, for metacal add-on I think the composite catalog should be doing exact matching (i.e., the row order should be exactly the same) and hence all returned arrays should be unmasked arrays. So maybe this issue is no longer relevant?

**Comment by yymao** [comment]
In [GCR v0.8.9](https://github.com/yymao/generic-catalog-reader/releases/tag/v0.8.9) one can now set `always_return_masked_array` to True to enable this.
