### ISSUE TITLE
Add back `dc2_object_run2.1i_dr1b_all_columns_with_photoz` and fix cache issue

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#406]
The config `dc2_object_run2.1i_dr1b_all_columns_with_photoz` has been removed but due to #405 it was left in the shared environment and have been picked up by users. The removed config did not have the cache option set correctly. 

We need to add this config back and fix the cache issue in the config. 

(cc @zdu863)

**Comment by yymao** [comment]
Actually, this catalog does exist but was renamed to `dc2_object_run2.1i_dr1_with_photoz`, with correct cache setting. 

@zdu863, can you update your code to use `dc2_object_run2.1i_dr1_with_photoz` instead?

**Comment by zdu863** [comment]
@yymao Yes, I'll do that, thanks.
