### ISSUE TITLE
Native Quantities Do Not Work With GCRQuery

### ISSUE THREAD

**Issue by adam-broussard** [LSSTDESC/gcr-catalogs#409]
I'm getting a SyntaxError when running the following code (for example):

```import GCRCatalogs
from GCR import GCRQuery
ha_fluxlim = GCRQuery((np.isfinite, 'emissionLines/totalLineLuminosity:balmerAlpha6563'), 'emissionLines/totalLineLuminosity:balmerAlpha6563 > %e' % 2.6e7)
cat = GCRCatalogs.load_catalog('cosmoDC2_v1.1.4_small')
data = cat.get_quantities(['redshift_true'], filters = (ha_fluxlim))
```

Apparently the fact that the emission line has a colon in the reference causes an error when evaluating the text expression in `necompiler.py` line 284.

**Comment by yymao** [comment]
Indeed. You can however use the `(func, *args)` construction:

```python
GCRQuery(
    (np.isfinite, 'emissionLines/totalLineLuminosity:balmerAlpha6563'),
    (lambda x: x > 2.6e7, 'emissionLines/totalLineLuminosity:balmerAlpha6563'),
)
```

**Comment by yymao** [comment]
Also, see https://github.com/yymao/easyquery#creating-query-objects for more usages.

**Comment by adam-broussard** [comment]
Ah, okay, I apologize.  Thank you for the help!
