### ISSUE TITLE
Add catalog config for Run 2.1i dr4 matched object-extraGalactic catalog

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#411]
@fjaviersanchez has prepared matched files between objectId for galaxies and the extraGalactic catalogs.  There are catalog configs for the Run 2.1.1i; and Run 2.1i dr1b.

This issue is to add one for Run 2.1i DR4.

**Comment by katrinheitmann** [comment]
Just a small question: how much effort is involved in this? Is it worthwhile to do this still for Run 2.1i or should we simply wait for the new, clean runs? Thanks!

**Comment by wmwv** [comment]
This is about 10 minutes of work.

**Comment by yymao** [comment]
@wmwv Are you plan to work on this or should we re-assign it to someone else?

**Comment by yymao** [comment]
Also need to add Run 2.2i catalogs.

**Comment by heather999** [comment]
Just noting here that we ran back across these dr4 files while completing our migration from projecta to the NERSC CFS.  The files live on within the now deprecated `/global/cfs/cdirs/lsst/projecta/lsst/groups/SSim/matched_ids_run2.1i_dr4_*.fits.gz`  We were wondering if they should finally be registered in GCR, or copied into the new CFS `shared` area.  Javier suggested we could just delete them if no one objects.  They can be quickly regenerated. 
I'm punting for now - but it would be nice to either include these or remove them.
