### ISSUE TITLE
Missing columns in GCR catalogs for 2.1

### ISSUE THREAD

**Issue by reneehlozek** [LSSTDESC/gcr-catalogs#413]
I'm trying to adapt some of the GCR tutorials to run on 2.1 (see [here](https://github.com/LSSTDESC/DC2-analysis/pull/127)) but am running into missing columns needed for those tutorials (in particular object_gcr_2_lensing_cuts.ipynb and object_gcr_3_challenges.ipynb).

The missing columns are:
ext_shapeHSM_HsmShapeRegauss_resolution
mag_i_cModel
shape_hsm_regauss_etot
ext_shapeHSM_HsmShapeRegauss_sigma
ext_shapeHSM_HsmShapeRegauss_e1
ext_shapeHSM_HsmShapeRegauss_e2

**Comment by wmwv** [comment]
IIRC, it may be the case that we didn't calculate a bunch of the shape information through HSM, etc. for the Run 2.1 run because we just moved on to metcal.

@johannct @EiffL Do I remember correctly about this?

**Comment by wmwv** [comment]
`mag_i_cModel` should be in there.  That's likely some error in `gcr-catalogs`.

**Comment by wmwv** [comment]
@reneehlozek You had also mentioned `snr_i_cModel`.  Are the additional ones?  Did you specifically not list quantities you knew were derived?

**Comment by reneehlozek** [comment]
oh shoot, not I wanted to list snr_i_cModel too, must have deleted that in my cut and paste

**Comment by yymao** [comment]
@reneehlozek @wmwv I think HSM is still being calculated. In fact, when I ran this only `shape_hsm_regauss_etot` is missing:

![image](https://user-images.githubusercontent.com/3792659/72917233-a70a8400-3d00-11ea-9028-8455dcd910a6.png)

@EiffL do you recall where `shape_hsm_regauss_etot` came from? This is not a quantity that we ever defined in GCR and I suspect it's a runtime user-defined quantity.

**Comment by johannct** [comment]
hmm so  is it a problem of different GCR version between @yymao  and @reneehlozek?
@wmwv I do not remember. The HSM of course are in the input parquet files from processing, but for 2.1 I have not been in the loop of the catalog creation, as far as I can remember.

**Comment by yymao** [comment]
@reneehlozek can you confirm that all the columns that you listed are indeed missing, or just `shape_hsm_regauss_etot` is missing?

**Comment by yymao** [comment]
I'm closing this because all the reported missing columns (with the exception of `shape_hsm_regauss_etot`) are all indeed present in Run 2.1i. 

`shape_hsm_regauss_etot` is a quantity added by user during runtime in the [object_gcr_2_lensing_cuts](https://github.com/LSSTDESC/DC2-analysis/blob/master/tutorials/object_gcr_2_lensing_cuts.ipynb) tutorial.

@reneehlozek, please reopen if this remains an issue.
