### ISSUE TITLE
Organize catalogs under new root dir in Community File System

### ISSUE THREAD

**Issue by JoanneBogart** [LSSTDESC/gcr-catalogs#424]
In order to
* minimize disruption
* avoid sym links from within catalog area to outside
* simplify porting process to another site
* avoid including any non-catalog files in the catalog area

we plan to copy just those directories and subdirectories actually containing catalogs to the new area, preserving the hierarchy so that paths mentioned in config files don't have to change, and pruning any subdirectories with no catalogs.
To be confirmed: any immediate parent directory of a catalog files does not also contain non-catalog files.

Once the full copy of projecta has been archived to tape and the new catalog area is complete, catalog files in the full copy will be deleted.

**Comment by JoanneBogart** [comment]
This is the list of directories containing catalogs known to GCR (current version in master):
`^/Buzzard/Buzzard-1/addgalspostprocess
^/Buzzard/Buzzard-2/addgalspostprocess
^/Buzzard/Buzzard-21/addgalspostprocess
^/Buzzard/Buzzard-3/addgalspostprocess
^/Buzzard/Buzzard-3/v1.9.2/addgalspostprocess/
^/Buzzard/Buzzard-5/addgalspostprocess
^/PhotoZDC2/COSMODC2v1.1.4/IMAGE/10_year_error_estimates
^/PhotoZDC2/COSMODC2v1.1.4/IMAGE/10_year_error_estimates/pipelinedir/outputs
^/PhotoZDC2/COSMODC2v1.1.4/PZCalibrate_image
^/PhotoZDC2/run1.2i/TRACTHDF5
^/PhotoZDC2/run1.2p/TRACTHDF5
^/PhotoZDC2/run2.1i_all_patches/outputs
^/SSim-DC2/
^/SSim-DC2/Run1.2
^/SSim-DC2/cosmoDC2_v1.1.4
^/SSim-DC2/example_instance_catalogs
^/SSim-DC2/reference_catalogs
^/cosmoDC2/all_v0.1.0
^/cosmoDC2/baseDC2_snapshots_v0.1/STEP247
^/cosmoDC2/baseDC2_snapshots_v0.1/STEP432
^/cosmoDC2/baseDC2_v1.1
^/cosmoDC2/cosmoDC2_v1.0.0_full_highres
^/cosmoDC2/cosmoDC2_v1.0.0_knots_addon
^/cosmoDC2/cosmoDC2_v1.1.3_rs_scatter_query_tree
^/cosmoDC2/cosmoDC2_v1.1.4_knots_addon
^/cosmoDC2/cosmoDC2_v1.1.4_rs_scatter_query_tree_double
^/descqa-catalog
^/production-DC2_ImSim/Run1.2i/dpdd/object_catalog
^/production-DC2_ImSim/Run1.2i/dpdd/object_catalog_alpha
^/production-DC2_ImSim/Run1.2i/dpdd/source_catalog
^/production-DC2_ImSim/Run1.2i/eimages/DC2-R1-2p-WFD-r
^/production-DC2_ImSim/Run2.1.1i/dpdd/calexp-v1:coadd-v1/metacal_table_summary/final
^/production-DC2_ImSim/Run2.1.1i/dpdd/calexp-v1:coadd-v1/object_table_summary/final
^/production-DC2_ImSim/Run2.1i/dpdd/calexp-v1:coadd-dr1a-v1/object_table_parquet
^/production-DC2_ImSim/Run2.1i/dpdd/calexp-v1:coadd-dr1b-v1/object_mcal_catalog_coaddv1_dr1b
^/production-DC2_ImSim/Run2.1i/dpdd/calexp-v1:coadd-dr1b-v1/object_table_parquet
^/production-DC2_ImSim/Run2.1i/dpdd/calexp-v1:coadd-dr1b-v1/object_table_summary
^/production-DC2_ImSim/Run2.1i/dpdd/calexp-v1:coadd-dr4-v1/object_table_parquet
^/production-DC2_ImSim/Run2.1i/dpdd/calexp-v1:coadd-v1/metacal_griz_catalog
^/production-DC2_PhoSim/Run1.1p/dpdd/object_catalog
^/production-DC2_PhoSim/Run1.2p/dpdd/dia_object_catalog_test
^/production-DC2_PhoSim/Run1.2p/dpdd/forced_source_catalog
^/production-DC2_PhoSim/Run1.2p/dpdd/object_catalog_v3
^/production-DC2_PhoSim/Run1.2p/dpdd/object_catalog_v4
^/production-DC2_PhoSim/Run1.2p/eimages/DC2-R1-2p-WFD-r/output/000008
`

**Comment by JoanneBogart** [comment]
The file hierarchies represented by sym links under the current root_dir at NERSC 
```
$ ls /global/projecta/projectdirs/lsst/groups/CI/gcr_rootdir_test
total 7
 Buzzard -> /global/projecta/projectdirs/lsst/groups/CS/Buzzard/
 PhotoZDC2 -> /global/projecta/projectdirs/lsst/groups/PZ/PhotoZDC2/
 SSim-DC2 -> /global/projecta/projectdirs/lsst/groups/SSim/DC2/
 cosmoDC2 -> /global/projecta/projectdirs/lsst/groups/CS/cosmoDC2/
 descqa-catalog -> /global/projecta/projectdirs/lsst/groups/CS/descqa/catalog/
production-DC2_ImSim -> /global/projecta/projectdirs/lsst/production/DC2_ImSim/
production-DC2_PhoSim -> /global/projecta/projectdirs/lsst/production/DC2_PhoSim/
```
will need varying degrees of special handling. The simplest is descqa-catalog. Almost everything directly under it is a regular file and a catalog. The few subdirectories should be pruned in the new cfs area.

**Comment by JoanneBogart** [comment]
@heather999 How about proceeding like this:
1. Make a new commit to gcr-catalogs on a branch which sets the root dir for NERSC site to `/global/cfs/cdirs/lsst/catalogs`
2. Copy directories listed above to new area, preserving hierarchy.  SSim-DC2 has to be handled a little differently from the others since we need both regular files under it and some of its subdirectories
3. Test that everything is working. (There is a test script in `gcr-catalogs` repo which checks that all catalogs can be loaded.)
4. As time permits, prune away non-catalogs, testing again to make sure nothing we need has been removed.
We could merge the branch to master and start using it as soon as 3. is done.

**Comment by heather999** [comment]
@JoanneBogart As discussed at the CS meeting yesterday, there are directories under `/global/projecta/projectdirs/lsst/groups/CS/cosmoDC2/` that we agreed could be copied to tape and removed from disk.  I transcribed Eve's list to this issue: https://github.com/LSSTDESC/DC2-production/issues/394  Is everything currently under `CS/cosmoDC2` referenced by GCRCatalogs?  I'm open to delaying the removal of those files until after this transition to CFS, which I gather may require GCRCatalog config modifications.

I'd like to understand better what directories/files under `/global/projecta/projectdirs/lsst/production/DC2_ImSim/` and `DC2_PhoSim` are referenced by GCRCatalogs.

For `descqa-catalog` I'd just want to alert @yymao and @evevkovacs I know they have already done work to migrate the DESCQA web app to CFS.

**Comment by JoanneBogart** [comment]
@heather999  The directories above are the ones referenced by GCR (and, I believe, the *only* ones referenced by GCR unless there are sym links referencing something outside). In all but one case they correspond to items in Eve's list of things to be permanently available on disk, but there are several items in her top list which are not referenced by GCR (and they are all under `CS/cosmoDC2` as well.

 None of the things mentioned in her bottom list are referenced by GCR.  They also are under `CS/cosmoDC2`.    I think both parts of Eve's list taken together cover all directories under `CS/cosmoDC2`
Here is a spreadsheet which includes here information about the things to be permanently saved together with the full collection of directories I was expecting we would copy for GCR:
https://docs.google.com/spreadsheets/d/1Jlqliy_6irmaEcT41Tg0OzcWV4gsrxfn1FPraIOPRI4/edit?usp=sharing

**Comment by sschmidt23** [comment]
There is a lot of non-catalog files in PhotoZDC2, particularly PhotoZDC2/COSMODC2v1.1.4, as several PZ members were using catalog files directly for spatial clustering work and decided to keep their files in a subdirectory.  COSMODC2v1.1.4 is 921GB, I'm pretty sure well under half of that is photo-z catalogs, so once it is copied over I will do tons of trimming to get rid of the cruft and unassociated research files.  Thankfully the runX.Y catalogs are much cleaner.

**Comment by yymao** [comment]
@JoanneBogart @heather999 thanks for getting this started! I wonder if we should ask in #desc-general / send out to all member mailing list to see if people are using these files outside of GCRCatalogs? I think some of these catalogs files are generated for other non-GCR purposes and the catalog creators probably just created a GCR config without thinking about file locations may be changed in the future.

**Comment by JoanneBogart** [comment]
@yymao absolutely - would be good to get this kind of information and make sure people are aware of coming changes.  
Assuming we knew in a general way what belongs in the new catalogs directory, there are several steps I imagine happening:
* NERSC copies all of projecta to some cfs directory
* We copy all directories containing useful catalogs, whether or not they are registered with GCR, to the new catalogs directory.   For those which are registered with GCR, relative paths should be preserved
* Previous step will most likely include some stuff which doesn't qualify as catalogs, so that needs to be pruned away
* Things in the new catalog area are deleted from the overall copy of projecta

Although I put the NERSC copy of projecta first I don't know whether it actually happens first. Otherwise I think the ordering listed is best for minimizing disruption.

**Comment by yymao** [comment]
@JoanneBogart the plan you listed sounds good, though we need to be particularly careful with the last step -- I believe there are people who access catalogs without using `GCRCatalogs` and we should ask them to change their code around Step 1 (even if they don't want to use `GCRCatalogs` to access the data, we should ask everyone use `GCRCatalogs` to get the data location.)

**Comment by yymao** [comment]
@JoanneBogart On a different note, I noticed some of the recently merged PRs contain configs files that escape our `root_dir` modification. For example, this one: https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/catalog_configs/dc2_object_run2.2i_dr3.yaml and likely a few more. 

Can you help update them to use the new `root_dir` construct?

**Comment by JoanneBogart** [comment]
@yymao Yes, sure.  I'll look into it tomorrow.

**Comment by JoanneBogart** [comment]
@yymao and @heather999  That file references the new cfs area so there is no very good way to  make it relative to the current (albeit temporary) default root dir under projecta.   I gather the idea with this file was to exercise the new cfs space.  I could change the path to make it relative to the new root dir but then it wouldn't be loadable because the corresponding directory (let alone the file) doesn't exist under the current default root dir.  In order to get everything to work with a relative file path we could
* create the proper file hierarchy in projecta and copy the file there and also
* (on a branch) add a new fake site to the dict associating root dir with site.   
Then to test out the file in the cfs location one would set the environment variable DESC_GCR_SITE to the fake site name.
Is this worth doing?   Or do we just wait until the new cfs area is fully populated?

**Comment by yymao** [comment]
I'd just want till the new cfs area is ready, and we should open an issue about this so that we don'd forget.

I think the main thing that we need to be careful with is that we should check if there's any config that points to projecta but does not use `^/` construct. If so then they might be missed during this migration so we need to make sure we got everything.

**Comment by sschmidt23** [comment]
I copied the PhotoZDC2 catalog data directories (only catalogs, not the extraneous files) to the new /global/cfs/cdirs/lsst/catalogs/PhotoZDC2 directory yesterday.  I changed the sym link to PhotoZDC2 in site_config/site_rootdir.yaml on a local copy of gcr-catalogs and tested things out, it looks like all of the PZ catalogs load properly and work.  I'll have to double check for any hard-coded references to 'projecta' of the type Yao mentioned in the previous comment, but I think PhotoZDC2 is all set (though that said I'm not going to delete the old data yet until someone else tests and I give a warning to users in the PZ channel of the move).

**Comment by yymao** [comment]
@sschmidt23 thanks. After some discussion among @JoanneBogart @heather999 @johannct, we decided to adopt a different organization scheme and not to use `/global/cfs/cdirs/lsst/catalogs`. We are almost ready with the new scheme. Stay tuned.

**Comment by heather999** [comment]
@sschmidt23 I've copied all the PhotoZDC2 catalogs under `/global/cfs/cdirs/lsst/catalogs/PhotoZDC2` to the new `shared` area: `/global/cfs/cdirs/lsst/shared/` as discussed on Slack:
`/global/cfs/cdirs/lsst/catalogs/PhotoZDC2/COSMODC2v1.1.4` to `/global/cfs/cdirs/lsst/shared/extragalactic/cosmoDC2/PhotoZDC2/COSMODC2v1.1.4`
and
the other run-specific areas: Run2.2i  run1.2i  run1.2p  run2.1i_all_patches
are copied to `/global/cfs/cdirs/lsst/shared/DC2-prod/RunX.X/addons`

**Comment by JoanneBogart** [comment]
@sschmidt23  It looks like the files under `/global/cfs/cdirs/lsst/catalogs/PhotoZDC2/COSMODC2v1.1.4/PZCalibrate_small` are a subset of those under `/global/cfs/cdirs/lsst/catalogs/PhotoZDC2/COSMODC2v1.1.4/PZCalibrate_image`
Also the file under `/global/cfs/cdirs/lsst/catalogs/PhotoZDC2/COSMODC2v1.1.4/10_year_error_estimates` appear to be a subset of those under `/global/cfs/cdirs/lsst/catalogs/PhotoZDC2/COSMODC2v1.1.4/IMAGE/10_year_error_estimates` 
Or am I missing something here?
If not, is it ok to get rid of the directories with the subsets?  As far as GCR is concerned, they're not necessary.

**Comment by sschmidt23** [comment]
Great, thanks!  So, I guess now that photo-z's live in more appropriate sub-directories, rather than one monolithic PhotoZDC2 directory, we will just have to update all of the relative paths in the config files relative to a new root directory, is that correct? Should be very simple to change.

**Comment by evevkovacs** [comment]
Yes, I think so. Everything is relative now, and there is also a new yaml parameter called "based_on" so that variants of a catalog can be based on one yaml file that has all the locations etc. (ie only need to change the one yaml file and all variants of the catalog go along for the ride)
Yao can provide examples
Eve

On 5/11/20 6:13 PM, Sam Schmidt wrote:

Great, thanks! So, I guess now that photo-z's live in more appropriate sub-directories, rather than one monolithic PhotoZDC2 directory, we will just have to update all of the relative paths in the config files relative to a new root directory, is that correct? Should be very simple to change.

**Comment by sschmidt23** [comment]
I saw a few examples in the new catalog_configs, it looks very handy for testing on one healpix pixel and such.

**Comment by JoanneBogart** [comment]
@sschmidt23 don't worry about the config files.  I'm updating everything in gcr-catalogs to match the new arrangement.  I'm getting close to finishing.
