### ISSUE TITLE
Add deprecation warnings when users load older catalogs that we plan to drop support

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#425]
As the number of catalogs in `GCRCatalogs` grows, we probably would want to start to drop support of the older versions of some catalogs, especially those that were created for testing or other temporary purposes. 

Before we do that, `GCRCatalogs` should print out clear deprecation warnings when users try to load them, so that we can make sure those catalogs are safe to be removed.

**Comment by yymao** [comment]
Let's at least start to collect the list of the "soon-to-drop-support" catalogs. I'd like to ask:

@evevkovacs - for protoDC2 and cosmoDC2
@j-dr - for buzzard
@wmwv @fjaviersanchez @johannct - for DC2 catalogs

**Comment by heather999** [comment]
Can we consider deprecating DC2 Run1.1p, as in:
https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/catalog_configs/dc2_object_run1.1p.yaml  ?
I'm not aware anyone would be seriously utilizing Run1.1p data at this point.  Soon I could imagine doing the same for Run1.2x, but there's some possibility people are still active on that data.

**Comment by katrinheitmann** [comment]
What does "deprecate" entail? The 1.2p/i runs are the only ones where we have the phosim/imsim pair. Maybe there is not a lot of traffic right now, but it is an important dataset. We are also still going to have it in the paper.

**Comment by johannct** [comment]
I think the initial phrasing of @yymao is correct : drop support of "older versions of some catalogs". In the case of 1.2, there is only one version. In general deprecation results from either the replacement of a functionality with another, or the dropping of features that cannot be supported anymore. In our case deprecation will thus results : 1/ in the first case from a new version of a given catalog (say we feel like reprocessing 1.2 with stack 19.0.0) or 2/ in the second case we just find ourselves short on storage and need to stage some low-usage catalogues.

**Comment by johannct** [comment]
For 1.1 specifically, I am not sure whether it can be considered as an early version of 1.2p, I just can't remember. If it can, we should deprecate it, as if asked by someone about using it, we would immediately answer "rather use 1.2p".

**Comment by evevkovacs** [comment]
@yymao protoDC2_v2.1.2, protoDC2_v3.0 and protoDC2_v5.0 should be kept.  All versions of cosmoDC2 currently in the catalogs area and previously listed by Heather and me also need to be retained for the forseeable future.

**Comment by yymao** [comment]
@katrinheitmann -- Here by "deprecate" or "drop support" I was referring to catalogs that users should not continue to use for science. As @johannct mentioned, that usually happens when there was a bug fix to the catalog, or when the catalog was meant for temporary purpose to begin with. 

In this sense, the most updated processed output of Run 1.1i, 1.1p and 1.2i should all be kept. I would agree with Eve that protoDC2_v2.1.2, protoDC2_v3.0 and protoDC2_v5.0 should be kept. 

Maybe at a later time we should employ the concept of "archive" to label some of these older, but should-be-keeped catalogs. But right now I am mostly asking catalogs that should not continue to be used.

**Comment by JoanneBogart** [comment]
@yymao How were you thinking to implement this? Maybe add a new keyword `deprecated` to the config file?

**Comment by yymao** [comment]
@JoanneBogart yep, that sounds very reasonable. And we can set its value to be the deprecation message, for example:

```yaml
deprecated: This catalog is no longer supported and may not be accessible in the future. Please use `cosmoDC2_c1.1.4` instead. 
```
(some of the general language can be integrated into the code that prints out the messages I guess)

With the recently merged #430 this should be easy to implement. I'll be happy to take a stab on this.

**Comment by yymao** [comment]
I am now working on a deprecation plan. I should emphasize that by deprecation we don't mean to remove these catalogs immediately, but to encourage people to switch to a more updated version (and also to let them have a chance to complain if they need the exact version). 

I'll start with an overall draft plan here. Some more details need to be worked out (especially for catalogs that have add-ons), but let's get the overall picture right first.

## ProtoDC2
- Deprecate protoDC2 v2.x (except for v2.1.2) -> ask people to use v2.1.2 or v5.0
- (Keep protoDC2 v2.1.2)
- (Keep protoDC2 v3.0)
- Deprecate protoDC2 v4.x -> ask people to use protoDC2 v5.0

## CosmoDC2
- Deprecate cosmoDC2 v0.1 -> ask people to use cosmoDC2 v1.0 or v1.1.4
- (Keep cosmoDC2 v1.0)
- Deprecate cosmoDC2 v1.1.3 -> ask people to use cosmoDC2 v1.1.4
- (Keep cosmoDC2 v1.1.4)

## Buzzard
- (Keep Buzzard high-res) 
- Deprecate Buzzard v1.6 -> ask people to use Buzzard v2.0
- Deprecate Buzzard v1.9.2 -> ask people to use Buzzard v2.0
- (Keep Buzzard v2.0)

## DC2 Runs
- Deprecate Run 1.1p -> ask people to use Run 1.2p v4
- Deprecate Run 1.2p v3 -> ask people to use Run 1.2p v4
- (Keep Run 1.2p v4)
- (Keep Run 1.2i)
- Deprecate Run 2.1i -> ask people to use Run 2.2i DR3

I guess I am most uncertain about Run 2.1i, but comments to any part of this draft plan are all welcome. 

One we finalize this I'll start to work out the details and the plan for some add-on catalogs. 

cc @evevkovacs @j-dr @katrinheitmann @jchiang87 @wmwv @johannct @fjaviersanchez @heather999 @JoanneBogart

**Comment by johannct** [comment]
As far as I can tell, for 2.1i : this is the prod with the problem in the AGN population; but it does have the DDF region filled in if I am not mistaken. 2.2i DR3 has no DDF tracts, but the AGN problem in the WFD region is "cured". In both cases, there are too shallow patches in some tracts and filter, due to a pipeline problem in managing downstream failure to compute sky correction after calexp production, for a given visit. Given this situation, I am not sure either if 2.1i should be deprecated at the same time as the other more obvious catalogues.

**Comment by johannct** [comment]
How about 2.1.1i?

**Comment by yymao** [comment]
Hmm, ok. So given that 2.1i has DDF I think we should keep Run 2.1i DR4 (and deprecate DR1 and DR3)? 

What's the difference between 2.1.1i and 2.2i? I thought the former was just a test run for 2.2i but I could be wrong. @jchiang87 @katrinheitmann what do you think?

**Comment by jchiang87** [comment]
Image-wise, 2.1.1i is a subset of 2.2i DR3, and was indeed just a test run for 2.2i. Assuming the region of the sky covered by 2.1.1i has been processed by the Stack for 2.2i, I think we are safe to deprecate 2.1.1i.

**Comment by yymao** [comment]
Thanks @jchiang87. Based on this I've updated the plan in the [comment above](https://github.com/LSSTDESC/gcr-catalogs/issues/425#issuecomment-630447618).

**Comment by heather999** [comment]
@yymao If we're keeping Run2.1i DR4 (I think we should) and deprecating the previous data releases, should we revisit: https://github.com/LSSTDESC/gcr-catalogs/issues/411 which would add the Run2.2i DR4 matched object-extraGalactic catalog that Javi prepared?

**Comment by yymao** [comment]
Yes, possibly. There are similar issues in other catalogs too (i.e., main catalog should be deprecated but some of its add-ons do not present for the newer version). 

I was planning to deal with all the add-on issues once we have agreed on the plan for main catalogs.

**Comment by evevkovacs** [comment]
@yymao Plan for extragalactic catlogs protoDC2 and cosmoDC2 is fine. Thanks.

**Comment by yymao** [comment]
Now that we have converged on the deprecation plan for main catalogs, I am looking into the issue of add-on catalogs. 

When a main catalog is going to be deprecated, its associated add-on catalogs will by default be deprecated as well. However, if the add-on product is not available for the main catalog's newer alternative (as listed [above](https://github.com/LSSTDESC/gcr-catalogs/issues/425#issuecomment-630447618)), then potentially some analysis will not be able use the newer alternative (due to the lack of necessary add-on). 

The best solution would be to generate the add-on products for those newer main catalogs, but this solution is of course subject to the availability of resource. Hence, some discussions may be needed.

Here I list all the occurrences of this issue (add-on products of a deprecated catalog have no counterpart for the newer alternative):

## redmapper addon for protoDC2 

Currently available for v2.0, v3.0, v4.3, among which v2.0 and v4.3 will be deprecated. No redmapper add-on available for their alternatives, v2.1.2 and v5.0, respectively. 

## photo-z for Run 1.2p

Currently only available for Run 1.2p v3, which will be deprecated. No photo-z add-on available for its alternative, Run 1.2p v4. 

## photo-z for Run 2.1i

Currently only available for Run 1.2p v3, which will be deprecated. No photo-z add-on available for its alternative, Run 1.2p v4. 

## Metacal for Run 2.1i

Currently only available for Run 2.1 DR1b, which will be deprecated. No photo-z  add-on available for its alternative Run 2.1 DR4. 

## Truth-matching add-on for Run 2+

Currently only available for Run 2.1 DR1b and Run 2.2.1, both of which will be deprecated. No truth-matching add-on available for their alternatives, Run 2.1 DR4 (see #411) and Run 2.2 DR3 (though Javi is [preparing one](https://lsstc.slack.com/archives/CBUMARLKC/p1589905182115700)), respectively. 


Tagging the add-on product providers here: @erykoff @sschmidt23 @johannct @EiffL @fjaviersanchez --- Do you think it is viable to generate these add-on for the "alternative catalog" named above. To be clear, those are:
- redmapper for protoDC2 v2.1.2
- redmapper for protoDC2 v5.0
- photo-z for Run 1.2p v4
- photo-z for Run 2.1p DR4
- metacal for Run 2.1 DR4
- Truth-matching for Run 2.1 DR4 and Run 2.2 DR3

Or, maybe some of these combinations of add-on/main products are no longer needed? 

Thoughts and comments welcome. 

cc @JoanneBogart @heather999 @katrinheitmann @jchiang87 @wmwv

**Comment by sschmidt23** [comment]
I should be able to produce photo-z's for run1.2pv4 and 2.1(i? I think there's a typo above) DR4. I was trying to finish up a ML photo-z catalog for cosmoDC2v1.1.4, I can work on generating these catalogs as soon as I finish that up.

**Comment by fjaviersanchez** [comment]
I can prepare a matched catalog for 2.1i Run dr4
