### ISSUE TITLE
Catalog configs that still use absolute paths and need to be updated

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#429]
Here's a list of catalog configs that still use absolute paths and need to be updated.

| Catalog | Path |
| ------- | ---- | 
| `dc2_metacal_run2.2i_dr3` | `/global/cfs/cdirs/lsst/production/DC2_ImSim/Run2.2i/dpdd/Run2.2i-dr3/metacal_table_summary` |  
| `dc2_object_run2.2i_dr3` | `/global/cfs/cdirs/lsst/production/DC2_ImSim/Run2.2i/dpdd/Run2.2i-dr3/object_table_summary` |  
| `hsc-pdr1-xmm` | `/global/cscratch1/sd/desc/hsc` |
| `photoz_run2.2i_dr3` | `/global/cfs/cdirs/lsst/catalogs/PhotoZDC2/Run2.2i` |
| `buzzard_v2.0.0_3` | `/global/projecta/projectdirs/lsst/groups/CS/Buzzard/Buzzard-3/v2.0.0/` |
| `cosmoDC2_v1.1.4_redmapper_v0.2.1py` | `/global/projecta/projectdirs/lsst/groups/CL/redmapper/cosmoDC2_v1.1.4` | 
| `cosmoDC2_v1.1.4_small_photoz_magerr_10y` | `/global/projecta/projectdirs/lsst/groups/PZ/PhotoZDC2/COSMODC2v1.1.4/IMAGE/10_year_error_estimates` | 
| `buzzard_v2.0.0_test` | `/global/projecta/projectdirs/lsst/groups/CS/Buzzard/Buzzard-3/v2.0.0/` | 
| `buzzard_high-res_v1.1` | `/global/projecta/projectdirs/lsst/groups/CS/Buzzard/Buzzard-highres` | 
| `baseDC2_5000_v1.1.1` and similar | `/global/cfs/cdirs/lsst/catalogs/baseDC2_5000_v1.1.1` |

**Comment by JoanneBogart** [comment]
All of these paths have been changed to relative in branch u/jrbogart/move-to-cfs
