### ISSUE TITLE
Default root dir not set on NERSC interactive queue nodes

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/gcr-catalogs#438]
Here's what I see on an interactive queue node at NERSC:
```
In [1]: import GCRCatalogs                                                      
/global/u1/j/jchiang8/dev/gcr-catalogs/GCRCatalogs/register.py:109: UserWarning: Default root dir has not been set!
  warnings.warn("Default root dir has not been set!")

In [2]: import socket                                                           

In [3]: socket.getfqdn()                                                        
Out[3]: 'nid00014'
```
This could be addressed by adding an `nid` entry in [site_rootdir.yaml](https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/site_config/site_rootdir.yaml) similar to the `nersc` entry.

**Comment by yymao** [comment]
Thanks @jchiang87. We'll fix it. 

For those who are looking for a temporary solution, you can run
```python
GCRCatalogs.set_root_dir("/global/cfs/projectdirs/lsst/shared")
```
and the catalogs should load as usual.

**Comment by JoanneBogart** [comment]
The non-interactive debug queue has the same behavior, returning only the node name (also a string starting with `nid` followed by digits); probably the other batch queues do as well.   I don't see anything in the `socket` module which can help.  I would guess it has to do with configuration of the nodes in such a way to keep them more isolated.
I'm wary of adding a `nid` entry to site_rootdir.yaml.  It might be ok for now, but we have no control over node names.  NERSC could change them at any time. 
There are also a couple lesser problems:
* values for `nersc` and `nid` have to be kept in sync
* conceivably socket.fqdn( ) could return a string which contains more than one of the keys in the dict. In this case the site value is not well-defined.  (This has been a possible failing all along, but the more keys we add, the more exposure we have.)

Unless we manage to come up with a more reliable way to discover site automatically (we tried before and couldn't), my preference would be to treat the automatic discovery of site as a convenience which works in many common circumstances, but should not be depended upon, especially not for production runs.  A more robust mechanism available now is to set the environment variable DESC_GCR_SITE to a recognized value, currently `nersc` or  `in2p3`.   This is already used at in2p3.

It is also possible to set the root dir directly (bypassing the concept of `site`) from python, but that should only be used when a catalog area other than the standard one needs to be accessed.

**Comment by jchiang87** [comment]
It would be useful to update the warning that's issued to provide info on possible ways to set the root dir if it isn't set by default.    I eventually discovered that I could set `DESC_GCR_SITE` to `nersc`, but I had to read through the code to find out about it.

**Comment by yymao** [comment]
@JoanneBogart In the absence of `DESC_GCR_SITE`, how about we just check if the root_dir path exists, and if so, set to it? Or combining the hostname + existing root_dir path?

**Comment by yymao** [comment]
@jchiang87 Indeed. Though I think when you see the warning it's too late to set `DESC_GCR_SITE` (it's set when `GCRCatalogs` is imported), but the warning can also mention `set_root_dir`.

**Comment by JoanneBogart** [comment]
No question we need to document this better and give more informative warnings.  I will see to that.
@yymao  I don't understand what you mean by `check if the root_dir path exists`

**Comment by yymao** [comment]
@JoanneBogart Something like this:

```python
for k, v in site_config.items():
    if os.path.isdir(v):  # and maybe also check if k in self._site_info:
        self._default_root_dir = v
        break
```

**Comment by JoanneBogart** [comment]
No, I don't think we should try to second-guess to that extent.  It's not impossible that two different keys will map to values which both exist at some site.    I would prefer to make the warning text more complete, explaining both alternate ways to get things set up.   If the root dir isn't needed (e.g., path in development config is absolute), the warning can be ignored.  Anyone else should fix the problem.

**Comment by yymao** [comment]
Agree that the warning should be more informative. 

On detecting hosts, it actually seems to that the path may be more unique than the hostname (i.e., the probability that a non-NERSC machine has a path named `/global/cfs/cdirs/lsst/shared` seems much lower than that its hostname contains `nid`), so I don't think that's second guessing.  And if we combine both the chance of misidentifying host would be much lower?

**Comment by yymao** [comment]
Right now the code looks like:
https://github.com/LSSTDESC/gcr-catalogs/blob/ecd6ba8bc406af9e8b7b82da5c1f9eecdb643a1b/GCRCatalogs/register.py#L103-L106

so it actually seems reasonable to add a second check on the root_dir path itself:

```python
    for k, v in site_config.items():
        if k in self._site_info and os.path.isdir(v): 
            self._default_root_dir = v
            break
```

**Comment by JoanneBogart** [comment]
I don't think this is a situation where we should be dealing in probabilities or artificial intelligence. It's not that big a burden to ask a user to do something explicit as long as they get timely information on what to do.

**Comment by yymao** [comment]
@JoanneBogart in that case, I think we should make it that a user can do something like `set_root_dir_by_site("nersc")`. I think it'd be unreasonable that a user has to look up the exact `root_dir` path everytime they use interactive queue.

**Comment by JoanneBogart** [comment]
Yes, such a function could be useful; I have no objection to that.  But I suspect that the most convenient thing for many such users  would be to put a line like
export DESC_GCR_SITE='nersc'
in .bashrc or other suitable set up file so they don't have to revisit it for every project they're working on.

**Comment by JoanneBogart** [comment]
We can also add a function which returns a list of available sites.

**Comment by JoanneBogart** [comment]
I was planning to put that list in as part of the warning message.

**Comment by yymao** [comment]
We have only two sites now so listing in the warning message is ok. A function to list them is good too. 

Re: setting `DESC_GCR_SITE` -- what you said is true but I am not sure if we really want to ask all users to set `DESC_GCR_SITE` in their own `.bashrc`. Maybe what we should do is to include that in the DESC python activation script? (cc @heather999)

**Comment by heather999** [comment]
Is this something we have to alert CC about for their own activation scripts @yymao ?

**Comment by yymao** [comment]
I think they already have one actually (this `DESC_GCR_SITE` was set up upon the request of @boutigny).

**Comment by boutigny** [comment]
Yes, I confirm that we had to force `DESC_GCR_SITE` on the notebook platform as it was not possible set it automatically.
