### ISSUE TITLE
astropy cosmology does not have sigma8

### ISSUE THREAD

**Issue by chihway** [LSSTDESC/gcr-catalogs#44]
With gc.cosmology, there is no cosmological parameters associated with the power spectrum amplitude... that seems like an important quantity to have. Maybe we need something beyond astropy?

**Comment by yymao** [comment]
The proposal is the following:
- add a new `CosmologyParameters` class in `GCRCatalogs` that the readers can use.
- `CosmologyParameters` will have the same call signature as the current CCL python wrapper.
- `CosmologyParameters` will have `to_ccl()` and `to_astropy()` methods.
- `catalog_instance.cosmology` will then return a `CosmologyParameters` instance **Note**: this is not backward compatible but at this stage it seems ok
