### ISSUE TITLE
An absolute path that we missed to change to relative

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#440]
I noticed this one config `cosmoDC2_v1.1.4_redmapper_v0.2.1py` that still contains an absolute path that we missed to change to relative:

https://github.com/LSSTDESC/gcr-catalogs/blob/ecd6ba8bc406af9e8b7b82da5c1f9eecdb643a1b/GCRCatalogs/catalog_configs/cosmoDC2_v1.1.4_redmapper_v0.2.1py.yaml#L5

**Comment by JoanneBogart** [comment]
This apparently was missed in the initial round changing from absolute to relative path.  The absolute path in question is unlike any of the ones I changed in that its old path was `projecta/projectdirs/lsst/groups/CL/redmapper/cosmoDC2_v1.1.4`.   Nothing else was under `groups/CL` 
Would
`shared/xgal/cosmoDC2/addons/redmapper_v1.1.4` be a reasonable place for it? If not, do you have a suggestion?

**Comment by yymao** [comment]
The new location you proposed looks good. Thanks!
