### ISSUE TITLE
Make reader for star truth parquet files

### ISSUE THREAD

**Issue by JoanneBogart** [LSSTDESC/gcr-catalogs#445]
Preferably should be general enough to handle sn truth parquet (not yet created).

**Comment by JoanneBogart** [comment]
I pushed a branch u/jrbogart/truth-parquet-reader which, with minimal testing, seems to handle star truth summary, sn truth summary, and sn variability truth. The largest of these files is 1.4 Gbytes.  It can load star variability truth (7.1 Gbytes) but all attempts to fetch data have failed with 
```
pyarrow.lib.ArrowIOError: Arrow error: Capacity error: BinaryArray cannot contain more than 2147483646 bytes, have 2147483647
```
even when I've included a cut to limit rows returned (but not rows searched).  Perhaps I can avoid this by reading in only a row group at a time. 

The reader also looks for potential native filters based on the value of the `filename_pattern` keyword in the config, but this is so far entirely untested.   It would be useful for galaxy truth, which is partitioned by healpixel, but I haven't yet made parquet versions of those (sqlite) files.

**Comment by JoanneBogart** [comment]
@yymao if you look at the reader much of it will look very familiar.  In particular, the class ParquetFileWrapper is nearly identical to the version in dc2_dm_catalog.py.   Ultimately I think it should be moved to a utility module or base class, but first it may need some enhancement to iterate over row groups.

**Comment by yymao** [comment]
@JoanneBogart thanks for the update! I'll try to take a look soon (was busy with another project this week). Do you want to open a draft PR (or a regular PR if it's ready) so that I can take a look using just the browser? :slightly_smiling_face:  Thanks!

**Comment by JoanneBogart** [comment]
@yymao  Sure, I'll open a draft PR if that makes it easier for you to look.  I think it's likely that we'll want to reorganize so utility code can just be in one place, but what I have now will give you an idea of where I'm headed.
