### ISSUE TITLE
Better naming scheme for photo-z addon/composite catalogs?

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#447]
When working on #446, I noticed that some photo-z addon/composite catalogs have inconsistent names. 

While we haven't enforced a strict rule for naming addon and composite catalogs, they should generally follow these example patterns below:

- Main catalog: `cosmoDC2_v1.1.4`
- Addon catalog: `photoz_v1_for_cosmoDC2_v1.1.4` (not for standalone use)
- Composite catalog: `cosmoDC2_v1.1.4_with_photoz_v1` (joining main and addon catalogs)

Consider those example patterns, I identified a few catalogs whose names are not consistent with the patterns:

- `cosmoDC2_v1.1.4_image_photoz_magerr_10y_PDFcat`: name suggests it's a composite catalog, but currently it's an addon for `photoz_magerr_10y_estimate_image`
- `photoz_magerr_10y_estimate_image`: name suggests it's an addon, but not clear for what (it's for `cosmoDC2_v1.1.4_image`). While the postfix `_image` gives a hint, it may actually be doubly confusing for people who are not familiar with these catalogs.
- `photoz_magerr_10y_with_pdfs`: name suggests it's an addon, but not clear for what catalog. However, this is actually a standalone composite catalog(! shouldn't this be an addon for cosmoDC2?) 

And then there's another kind of inconsistency:

- `pz_calibrate_references_cosmoDC2_v1.1.4_image` and `pz_calibrate_references_cosmoDC2_v1.1.4_small`: correct addon naming scheme but prefix should be `photoz_`. 

Since we are doing some catalog deprecation, it may be a good time to fix some of these inconsistency. Thoughts, @sschmidt23?

**Comment by sschmidt23** [comment]
Yes, the messy naming scheme has been on my to-do list for a while, I'll try to bump it up in priority.
