### ISSUE TITLE
Add ML photoz for cosmoDC2_v1.1.4_image

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/gcr-catalogs#457]
As an alternative to template-based BPZ, and to have an example of an machine learning based photometric redshift code, add photo-z's computed with FlexZBoost to gcr-catalogs for cosmoDC2_v1.1.4_image (at least the subset with i<26.5, as is done for BPZ)

**Comment by yymao** [comment]
Fixed by #467
