### ISSUE TITLE
Add photo-z's for Run2.2i_dr6a

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/gcr-catalogs#462]
Several grad students want to use run2.2i_dr6 data for blending studies, so I want to add photo-z's for this dataset.

**Comment by sschmidt23** [comment]
I created a branch to address this [here](https://github.com/LSSTDESC/gcr-catalogs/tree/issue/462/run22idr6a_photozs).  The reader for this works now, but I have an absolute path to a temp directory in the PZ WG area for the photoz parquet files. I do not have write permission to move the relevant parquet files to /global/cfs/cdirs/lsst/shared, so I need someone with permissions to copy the 78 parquet files currently in:
/global/cfs/cdirs/lsst/groups/PZ/PhotoZDC2/run2.2i_dr6_test/outputs/finished
to a new directory:
/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/addons/photoz/dr6
at which point I can update the current absolute path to the more appropriate relative path and then create a PR to merge this.

**Comment by yymao** [comment]
@sschmidt23 --- you can open a ticket in https://github.com/LSSTDESC/desc-help/issues ask for data copy and reference this issue.

**Comment by heather999** [comment]
Issue https://github.com/LSSTDESC/desc-help/issues/19 opened and the copy into the shared area is now complete

**Comment by yymao** [comment]
Closed by #463
