### ISSUE TITLE
cosmoDC2_image photo-z composite catalogs often fail to load

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/gcr-catalogs#465]
Due to the large sizes of the photo-z add_on catalogs for cosmoDC2_v1.1.4_image and the need to load the entire catalog because only a subset of the rows have photo-z's, and those are matched by galaxy_id, the catalog often causes memory problems when `photoz_pdf` (an array or 300 floats for every galaxy) is included in the queries.  The matching scheme currently used means that this problem is not solved with return_iterator=True or using a native filter.

A potential solution is to switch the matching scheme to MATCHING_FORMAT and also reading in a pre-computed mask.  This would enable using the iterator and native_filters, and generally improve functionality.

**Comment by yymao** [comment]
Fixed by #466
