### ISSUE TITLE
Add reader for random forest photo-z's for subset of cosmoDC2_v1.1.4_small

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/gcr-catalogs#479]
@MarkusMichaelRau asked about creating a catalog reader for a catalog of photo-z's created using a random forest algorithm for a subset of cosmoDC2_v1.1.4_small.  The catalog has a slightly different set of columns and is all stored in a single parquet file, so it will need a few tweaks compared to the nominal setup for the other extragalactic catalog readers.

**Comment by yymao** [comment]
Closed by #481
