### ISSUE TITLE
attribute `sky_area` missing in protoDC2 reader

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#49]
@dkorytov during the stream of PRs, it seems that we forgot to add attribute `sky_area` to the protoDC2 reader, and @duncandc noticed this. Can you put it back in? Thanks!

**Comment by dkorytov** [comment]
This fixed in the newest PR.

**Comment by yymao** [comment]
Thanks @dkorytov. This is now closed as it is fixed in #48
