### ISSUE TITLE
Enhance protocols for site, root_dir variables to better support users not at a standard site

### ISSUE THREAD

**Issue by JoanneBogart** [LSSTDESC/gcr-catalogs#499]
Currently a warning is issued if the site variable isn't set, but that is about to be normal for many users.  We need an easy way to disable the warning under some circumstances.

**Comment by JoanneBogart** [comment]
Depending on what we can do during the installation procedure, maybe something like the following could work:
* Change the sites file (GCRCatalogs/site_config/site_rootdir.yaml) by adding and entry for another site called something like 'local_user'.   In the tagged version of GCRCatalogs to be distributed the corresponding path would be `None`
* Whatever we come up with for distributing and installing the code and requested catalogs will have to ask for a value for root_dir.   When that is known, something on the client side should edit site_rootdir.yaml, changing `None` to the root_dir value supplied by the user
* Modify the code in _get_site_info to accept local_user as site if the value is not `None`. Some decision has to be made about which method of determining site takes priority.  My first guess at priority is
1.   use site_from_env   if supplied
2.  use value for local_user if not `None`
3.  use site_from_socket   (issuing a warning if we get to this point and site_from_socket can't find anything)

@yymao @heather999   1) Is this feasible (that is, is there a way to edit a file within GCRCatalogs during the install process)?   2) Does it adequately address the issue?

**Comment by yymao** [comment]
@JoanneBogart Thanks for the proposal. I am not sure how to edit a file during installation, and feel this process may requires more work (we have to provide a way to edit the installed yaml file if one made a typo during installation or move the root dir). 

My preference would be allowing user to set environment variable `DESC_GCR_ROOT_DIR`. The current environment variable `DESC_GCR_SITE` will still work as it does now and obtain root dir from the site config yaml file, while `DESC_GCR_ROOT_DIR` will just set the root dir directly. 

In other words, the `RootDirManager` will first check `DESC_GCR_SITE` and see if it can obtain a root dir. Then it checks if `DESC_GCR_ROOT_DIR` is set, and if so, sets root dir to `DESC_GCR_ROOT_DIR` (it can print a warning if it is overwriting `DESC_GCR_SITE`'s path). If both are not set, print out a warning too. 

Looking at the [`RootDirManager` init code](https://github.com/LSSTDESC/gcr-catalogs/blob/v1.0.4/GCRCatalogs/register.py#L108), I think we just need to add this check of `DESC_GCR_ROOT_DIR` into current line 121, and can leave other part mostly unchanged.

**Comment by JoanneBogart** [comment]
@yymao  I agree we don't want to do anything which requires a lot of extra work.  It would be best if we could come up with a scheme which automatically sets the local root dir at installation time, but if that's not possible without a lot of work it could be done by providing a script, something like the one in the draft PR I just created, which would only need to be called once.  (It has an --override option in case there was a typo the first time around or there actually is a legitimate reason for changing root_dir.)   Part of the installation instructions would document how the script is to be called.

The setting of the site is intrinsically a one-time (or nearly one-time) thing.   If we instead depend on the environment variable DESC_GCR_ROOT_DIR being set, we're asking the user to come up with some scheme which will reliably set it correctly every time he/she uses it.  Also there is no record of exactly what the user did if there are problems.  I'd rather stick with a single primary concept - site - for setting the root dir.  Developers might need more flexibility, but someone using the public release who is not a member of DESC is unlikely to.

**Comment by yymao** [comment]
@JoanneBogart is the script already in the PR? I only see the updated site config file currently in #503. 

There are few reasons I still think `DESC_GCR_ROOT_DIR` is the favorable approach:

1. Using environment variables to set paths is a common practice and is what most people would expect. Many common packages use environment variables to set cache paths, config paths, library paths, etc., and most users would be familiar with, and even expect, this practice. 
2. Using an environment variable is easier to debug. Users can simply `echo $DESC_GCR_ROOT_DIR` to see if the path is set correctly, without the need of loading GCRCatalogs or digging into their python installation directory.
3. If setting `site_config/site_rootdir.yaml` requires running a script, users will need to run that script every time they update GCRCatalogs. While the environment variable will be left intact from GCRCatalogs's update.
4. Site is not the primary concept in GCRCatalogs. I think this may be the key point that our opinions differ, since you mentioned that:
    
    > I'd rather stick with a single primary concept - site - for setting the root dir.
   
    In my view, root dir is the really primary concept here, and site is just to an convenient function for setting it. This manifest in both the name and implementation of `RootDirManager`. At module lelve, we allow users to set root directory using `set_root_dir` at run time, and provide convenience function `set_root_dir_by_site`. These features to me indicate that site is as auxiliary, while root dir is more important to GCRCatalogs.

**Comment by JoanneBogart** [comment]
Sorry; I thought I had pushed the script but I hadn't.   It's there now, in directory `scripts`.

1.   It may be a common practice, but I don't think it's invariably the best solution.  It's up to the user to decide how to ensure that the variable is set correctly for every use; that's not something we can package up easily, if at all.    When setting an environment variable is part of the procedure, it's also common for users to have problems because they've forgotten to do it, or are using some leftover setting which is incorrect.  I've had to track down many such problems - other people's and my own.
2.  I don't think it's easier to debug.  It requires that the user echo the variable at the right time, in the right console window.  It can be difficult to confirm remotely that that's what the user has done. In the scheme I propose anyone debugging or helping with debugging can reliably find out the value that was used.  It's not hard to give a prescription for finding the file.
3.  This is true, but normally updates to GCRCatalog happen less frequently than invocations of GCRCatalog.  If it's part of the install procedure, it can be well documented.  And, although I agree with you that we can't automate it in time for this release and shouldn't put in the effort to try, I still think it might be worth exploring later.  Public release users are unlikely to need to update their install of GCRCatalogs unless new catalogs are released, in which case they will again have to specify the install location in order to download.
4.  I agree "primary" was not the right word to express what I meant.  The root dir is the underlying concept that makes it go; in that sense it's primary.   Site dir provides a higher level interface which should be preferred when applicable.   There are people who need to manipulate root dir directly; that doesn't mean it's the right approach for everyone.  In particular, I would argue that non-DESC people using the public release are especially unlikely to need to change the value of root dir.  DESC people can continue to use GCRCatalogs however they have in the past.

**Comment by yymao** [comment]
Maybe it's better to chat by voice on this? I think we may be thinking of the user installation process somewhat differently. 

Thanks for pushing the script though. However, I don't think we should edit the files within installed python packages. It is not a good practice and I learned my lesson with fast3tree. If you think a file is more tractable than an environment variable for setting the root dir, the script should write the user's chosen root dir to something like `~/.config/desc/grc_path` instead of overwriting the installed python packages. 

I still don't think that the use of site it to provide a higher level interface. I think the concept of a site is only relevant in the DESC context, as we want to maintain the root dir based on the DESC site. Maybe what you have in mind is more like an alias. For example, maybe you are thinking that if a user put download data in `"dr6": "/gcr/root/dir/a"` and `"dr2": "/gcr/root/dir/b"`, then they can switch between these two paths quickly.  That's true, but we should be careful with overloading the concept of "site" with "root dir alias/shorthand".

**Comment by JoanneBogart** [comment]
Yes, we should talk.

> However, I don't think we should edit the files within installed python packages. It is not a good practice and I learned my lesson with fast3tree.

I don't have experience with this myself; you may be right.  I'd be interested in hearing what the problems were and will meanwhile think about the config file strategy.  

> Maybe what you have in mind is more like an alias.
No, I'm not thinking of it as an alias.   I think the idea of "site" is just as valid for somebody's laptop as it is for a facility like NERSC or IN2P3.   The difference is that  the site is not shared by many users. There is no way to set the associated path without input from the user(s). This holds as well for a facility like NERSC, but in that case an infrastructure person like Heather can decide on the path for everybody and we can put it explicitly in the package before release.  But even for a laptop, for users who aren't active developers, it's still the case that there is a centrally maintained area where the datasets go which doesn't normally change from session to session.

**Comment by yymao** [comment]
The main issue I encountered with asking users to edit files in installed python packages is that not all users have edit permissions (even on their local machine) depending on how the installation is done. Also, it may cause ambiguity when creating new environments based on existing environment.  

But let's step back for one moment. It seems to me there are two distinct questions:

1. Where the root dir is recorded: so far we discussed (1a) a file in the package (e.g., `GCRCatalogs/site_config/site_rootdir.yaml`), (1b) a file not in the package (e.g. `~/.config/desc/grc_path`), and (1c) an environment variable (e.g., `DESC_GCR_ROOT_DIR`)
2. Whether the root dir should always be coupled with a site name -- your proposal is that for non-DESC member, the site name would be  `local_user`. 

I am happy to discuss (1) actually. I think I am mostly opposed to (2). I don't think in our design, a root dir always needs to be coupled with a site name. I think `GCRCatalogs` can and should function fine as long as root dir is provided, even without a site name.

**Comment by JoanneBogart** [comment]
Starting with 2 - I don't think a root dir always needs to be coupled with a site name.  There are ways now to set it independently of site and I'm not advocating we eliminate that.  I do think, for non-DESC members, it would be best to couple it with a site name or, more generally, to make it - that is, the establishment of a default value - part of the installation process.   (Since we already have a mechanism for associating root dir with site, my script builds on that.)  Anyone can still override the value coming from site by other means. 

This is related to your remark that problems have arisen having to do with permissions.  The installer and the user need not be the same person (or account); in fact for a multi-user facility they're normally not.  I see the establishment of a default value for root dir as a function of the installer role, not the user role.

**Comment by JoanneBogart** [comment]
I found a package [config-path](https://pypi.org/project/config-path/) which comes close to fulfilling 1b above.  It's platform-independent, but doesn't provide a nice subfolder structure.  With code like this

```
from config_path import ConfigParser
conf_path = ConfigPath('desc', 'gcr_catalogs', '*.yaml')
write_path = conf_path.saveFilePath( )
```
returns `/global_homes/j/jrbogart/.config/gcr_catalogs.desc.yaml`

It could be modified to make subfolders instead, but that would take time and I'm not sure how I'd test it on Windows.   
I'll search a little while longer.

**Comment by JoanneBogart** [comment]
Maybe all I need is something like this:

os.path.join(os.path.expanduser("~"), ".config", "desc", "gcr_catalogs.yaml" )

**Comment by yymao** [comment]
Here's what I would suggest, to respect user's setting if exists:

```python
if os.getenv("XDG_CONFIG_HOME"):  # Unix
	user_config_dir = os.getenv("XDG_CONFIG_HOME")
elif os.getenv("LOCALAPPDATA"):  # Win
	user_config_dir = os.getenv("LOCALAPPDATA")
else:
	user_config_dir = os.path.join(os.path.expanduser("~"), ".config")

desc_config_dir = os.path.join(user_config_dir, "lsstdesc")
os.makedirs(desc_config_dir, exists_ok=True)

gcr_config_path = os.path.join(desc_config_dir, "gcr_catalogs.yaml")
```

**Comment by JoanneBogart** [comment]
Ok.  I had tried something just based on the fixed path and it worked all right.  Respecting user settings makes sense; it will complicate instructions a bit, though.

I don't understand the need to make directories.  Isn't this just for reading?

**Comment by yymao** [comment]
How would `gcr_catalogs.yaml` show up at the first place?  I thought we will provide a script/function to write it in?

**Comment by JoanneBogart** [comment]
..and I thought you were opposed to scripts, which people might not always know how to find!  I was assuming the user would be responsible for creating the file, but I have no problem with reviving the script (modified to use this location).

**Comment by JoanneBogart** [comment]
In that case I would be inclined to add something to utils.py to find the path, optionally creating directories, so it could be called from the script and also from RootDirManager

**Comment by yymao** [comment]
I still don't quite like the idea of have a loose script that is not integrated with the package. But we could provide something like:

```python
import GCRCatalogs
GCRCatalogs.set_root_dir("....", write_to_config=True)
```

?

**Comment by JoanneBogart** [comment]
It would be distributed with the package (that is, the script itself would be in a directory, e.g. `scripts`, under gcr-catalogs).        The possible issue with that would be making it easy for the user to find it and call it at the command line.
