### ISSUE TITLE
`size` and `size_minor` in SCHEMA.md but not in cosmoDC2?

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/gcr-catalogs#569]
The lensed total semi-minor and semi-major axes of the profiles seem to be missing from `cosmoDC2_v1.1.4_image` but appear in the documentation [here](https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/SCHEMA.md). Do we prefer to provide these quantities or would it be better to just remove them from the Schema? (Or do they exist and I just didn't see them?)

**Comment by evevkovacs** [comment]
We intended that users would compute the quantities they really wanted themselves from the magnification and the true sizes.  It's the area that gets multiplied by the magnification, so we thought it best that users define the area they need. I think it would probably be best to drop the lensed sizes from the schema (but happy to hear arguments against).

**Comment by yymao** [comment]
I am not sure if we should remove them from the schema table though. I think some other catalogs have `size` and `size_minor` defined, while cosmoDC2 doesn't. In `SCHEMA.md` it does say:

> Not all quantities listed below are available in all catalogs. Use `list_all_quantities()` to find available quantities.

Maybe we just need to make this line more prominent?  Suggestions (or even a PR) welcome.

**Comment by fjaviersanchez** [comment]
Thank you @yymao! I missed that! It looks to me then that either we include which catalogs include which quantities (I guess that `size_minor` and `size` are from Buzzard then?) or we leave the schema as it is. I'm leaning towards leaving it as it is because maintaining the schema with each quantity that belongs to each catalog may be a nightmare.

**Comment by evevkovacs** [comment]
Yes, agreed!
