### ISSUE TITLE
Need to change site_config to match the new catalog root directory at CC-IN2P3 

### ISSUE THREAD

**Issue by boutigny** [LSSTDESC/gcr-catalogs#571]
Following the introduction of a new CephFS file system at CC-IN2P3 some reorganization occurred and the GCRCatalogs root directory has been moved from /sps/lsst/data/desc/gcr_rootdir  to /sps/lsst/groups/desc/shared.
I am creating a PR to reflect this change in site_config

**Comment by yymao** [comment]
Fixed by #572
