### ISSUE TITLE
docker build test failed due to missing desc env

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#592]
docker build test now fails due to missing desc env, see
https://github.com/LSSTDESC/gcr-catalogs/runs/6135638876?check_suite_focus=true#step:11:11

Is this due to a rename of the environment in the docker image? I wonder if @heather999 would know.

**Comment by heather999** [comment]
I’ll take a look tonight!

**Comment by heather999** [comment]
I have fixed up the docker build process for desc-python:bleed.  This also led to a reorganization and migration away from creating a "desc" conda env, and instead we're just updating the conda "base" environment.  I'll branch and open a PR with any needed updates to the GH workflow.

**Comment by heather999** [comment]
hmm.. see it's still failing.. looking

**Comment by heather999** [comment]
Realized that lsstdesc/desc-python:latest also needed to be updated.  I've put a temporary fix on that for now which will allow the gcr-catalogs test to complete while I get that build procedure updated more properly next week.  Just re-started the GH action and will see if that takes care of it.
