### ISSUE TITLE
Add Av and Rv to the reader for protoDC2

### ISSUE THREAD

**Issue by evevkovacs** [LSSTDESC/gcr-catalogs#70]
Av and Rv are required by the schema and should be supplied by the reader. These quantities are needed for image sims and should be subjected to readiness testing.

**Comment by yymao** [comment]
Thanks @evevkovacs. 

@danielsf also pointed out a [code reference](https://github.com/LSSTDESC/sims_GCRCatSimInterface/blob/master/python/desc/sims/GCRCatSimInterface/CatalogClasses.py#L37) which I think would be useful when we implement this in the protoDC2 reader.

**Comment by dkorytov** [comment]
So I've implemented the Av & Rv quantities. There are infinities in both of them and Rv has NANs when the denominator is zero with an non-zero numerator. 

Here's a distribution of Av (2nd figure is just a zoom in ) 
![image](https://user-images.githubusercontent.com/25048061/35240018-c1b0b702-ff77-11e7-8017-8ae04d45d1e1.png)

Rv
![image](https://user-images.githubusercontent.com/25048061/35240123-0cb943f4-ff78-11e7-8076-3802e959b75e.png)

Do these look reasonable? I don't have any feel for Av/Rv.

**Comment by dkorytov** [comment]
@danielsf, I forgot to mention you in the above post.

**Comment by evevkovacs** [comment]
The distribution for Av looks reasonable I think. The infinities are probably due to a failure in the dust model extrapolations. Andrew B worked hard on these, so maybe not so much room for further improvement.  As long as it is just a handful, it should be acceptable. Rv for the Milky Way is 3.1, so I think Rv looks ok too, but @danielsf should comment.

**Comment by danielsf** [comment]
@dkorytov For my own sanity: what are

1) the total number of galaxies with Rv<0
2) the total number of galaxies with |Rv| > 5
3) the total number of galaxies in the sample (so I can see (1) and (2) as fractions)

Thanks

**Comment by dkorytov** [comment]
@danielsf here it is:
Rv<0 / total = 3097/18265 = 0.1696
|Rv| > 5 / total = 3285/18265 = 0.1799

The sample isn't too large because I'm using a small test catalog on my laptop.

**Comment by danielsf** [comment]
Rv>5 sounds large to me (though, admittedly, I am not an expert on interstellar dust in any galaxy).  If your sample is representative, and ~ 20% of galaxies are showing such high Rv values, we should put some effort into figuring out whether that is okay.  Whether "some effort" means consulting someone who is an expert or doing a quick literature search depends on whether we

a) know any dust experts or
b) have time to do a quick literature search

**Comment by evevkovacs** [comment]
Pinging @abensonca. Rv and Av distributions derived from the B and V filters and the dust corrections are shown above along with some outlier fractions. The outlier fractions that Dan quoted seem a bit large.

**Comment by dkorytov** [comment]
My sample should be representative, it's a small ra/dec cut out but out to same redshift. I'll rerun on the full catalog just to be sure. 

Just for reference here is the r-band & Rv relation:
![image](https://user-images.githubusercontent.com/25048061/35249620-4fc31876-ff98-11e7-9a41-2931c2ab95d3.png)

**Comment by abensonca** [comment]
Agreed. Those outlier fractions do seem large. The Av distribution looks ok - since there are infinities in there we should probably try to fix that though - it's probably just a case of figuring out what input (to the interpolator) quanity is bad for those cases and trapping it.

For Rv I agree we should try to get a sense of whether these values are unreasonable or not. As always, it's entirely possible that the dust model is working ok, but that the input galaxy properties are unreasonable. In either case if there are obvious bad things about these outlier galaxies we can attempt to catch them - but since the Rv distribution looks reasonably continuous we're probably stuck with these unless we can improve the galaxy and/or dust model.

**Comment by abensonca** [comment]
For the Av infinities - as usual if we can extract a handful of galaxies that show this problem and locate the original Galacticus files that contain them I can track back through the calculation and see what went wrong. (This would be useful to do right now since I re-wrote the dust post-processing recently so I'd want to check if the same problems still occur.)

**Comment by evevkovacs** [comment]
These dust corrections were all computed with the old perl code. The new python code has only been used for the galaxies with z > 1. If Dan can identify a file with Av infinities, I can rerun the dust corrections on that file using the new code to see if the problem is reproduced.

**Comment by abensonca** [comment]
ok - that sounds like a good plan.

**Comment by dkorytov** [comment]
An example infinity Av galaxy: 
nodeIndex: 1288029815550519306
In file on datastar: /media/luna1/kovacs/galacticus/results/galacticus_outputs_v0.9.4/AlphaQv3LB_dust_ELG_linked/nbody_AlphaQ_z1.1_BH_SDSS_LSST_BV_ELG_SEDval44/AlphaQv3LB_split_75/galacticus_AlphaQv3LB_split_75_nbody_AlphaQ_z1.1_BH_SDSS_LSST_BV_ELG_SEDval44.hdf5

**Comment by evevkovacs** [comment]
Please see the 2 galacticus files: galacticus_AlphaQv3LB_split_75_perl.hdf5 and galacticus_AlphaQv3LB_split_75_python.hdf5 in my usual downloads directory www.hep.anl.gov/kovacs/downloadsloads/dust. The _perl file was run with the old dust code and should contain the galaxy mentioned above. The -python file was made with the new code.@dkorytov can specify the snapshot in which to look.

**Comment by dkorytov** [comment]
It's in snapshot 286.

**Comment by abensonca** [comment]
For nodeIndex=1288029815550519306 I find Av=infinity in both the original (Perl) and new (Python) implementations of the dust calculation. Looking into why this happens, the dust postprocessing code is working OK - it's simply that this galaxy has an unrealistic size - it's far too small which results in extremely dense gas and so the optical depth is unreasonably high. This then causes the luminosity in the V-band to be zero (i.e. exp(-tau)=0 to machine precision) so we get infinite Av.

So the solution would be to fix the galaxy size. I could look into this, but it's not obvious that the issue can be resolved completely. Specifically, this galaxy lives in a halo which is right at the resolution limit of the simulation - so as far as my code can see that halo appears to come into existence instantaneously - given that we shouldn't necessary expect there to be reasonable properties for the galaxy in it.

This is something of a fundamental problem: we need at least ~10 particles to find and characterize a halo in an N-body simulation, and then for the galaxy calculation we probably want to resolve that halos progenitors down in mass by at least a factor 10 also to get reliable galaxy properties. So, that means the smallest halos for which you could reasonably trust the galaxy properties are ~100 particles (and I'm being generous in these estimates, so realistically you probably want even more particles). But, for a cosmological volume that gives unacceptably poor resolution.

So, I'll take a look at this case, but there may be no good solution.

@evevkovacs  can you figure out the merger tree file which this problem galaxy came from? I'll then re-run it and see if I can figure out why the size calculation fails.

**Comment by evevkovacs** [comment]
The merger tree file is called AlphaQ_split.75.hdf5, and is in the same directory: www.hep.anl.gov/kovacs/downloadsloads/dust.  However, there are always going to be a few outliers like this, for which a calculation fails. For the galsampled protoDC2 we can add some checks to throw out galaxies with obvious problems.

**Comment by abensonca** [comment]
Thanks. I'm happy to _not_ look into this if we're ok with these outliers.

**Comment by evevkovacs** [comment]
@abensonca Yes, please shelve it for now. I think we have a work-around and I would like to get a better idea of what the outlier fractions are for the various quantities.

**Comment by dkorytov** [comment]
I'm ready to submit a PR for adding Av & Rv to the GCR. It seems the issues are coming from the dust model and not the GCR.

**Comment by yymao** [comment]
Note: https://github.com/LSSTDESC/sims_GCRCatSimInterface/issues/9 depends on this

**Comment by yymao** [comment]
This is now fixed by #74.
