### ISSUE TITLE
add `stellar_mass_disk` and `stellar_mass_bulge`

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#72]
@dkorytov mentioned that we should use stellar mass to check if the disk/bulge component exists. Hence, I think we should add `stellar_mass_disk` and `stellar_mass_bulge` to the protoDC2 reader as well as the schema, so that the user does not need to know the native labels.

**Comment by rbiswas4** [comment]
@yymao The current protoDC2 catalog seems to have the columns `totalMassStellar` and `diskMassStellar` which I was playing with. I assumed that the difference would be due to the bulge in this model, and was ignoring some other component like gas maybe? 

But does your issue mean that I misinterpreted  the variables or the ones you are talking about?

**Comment by yymao** [comment]
@rbiswas4 not really --- many quantities in these catalogs have two names: one is whatever the catalog creators have been using, and the other one is what the CS WG has agreed on. 

The columns you mentioned are the former (our jargon for them is "native quantities"), which are total fine to use, but you should consider those labels "unstable" (label name may change, unit may change, etc). This issue is proposing creating "stable" labels for these columns. 

Does that make sense?

**Comment by yymao** [comment]
Note: https://github.com/LSSTDESC/sims_GCRCatSimInterface/issues/10 depends on this

**Comment by rbiswas4** [comment]
@yymao Yes, that makes sense. (I had gotten these by listing all quantities including native ones), but it is good to know, that I should be looking for non-native quantities for an API. (From the naming, I had assumed that native were the catalog builder's quantities and the rest were `derived` off those). But having well defined standard variable names for the public API use is the right way to go. 
 Off topic, and definitely not high on any priority, but the name`list_all_quantities` with default of `native=False` was a bit of a gotcha, even though its usage is definitely well documented.

**Comment by yymao** [comment]
@rbiswas4 The idea here is that, for a regular quantity (i.e., stable, not *native*), the user ought to be able to find its unit and definition [in the schema](https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/SCHEMA.md).  On the other hand, for a native quantity (i.e., unstable quantity), the user has to guess or ask the catalog provider for detail and know that its name or definition may change in the future.

And that's reason why `list_all_quantities` by default does not list native ones, as they are considered "not supported". Nevertheless, a power user (like you, in this case 🙂) can still access them when needed.
