### ISSUE TITLE
Add size_minor to schema and gcr reader

### ISSUE THREAD

**Issue by evevkovacs** [LSSTDESC/gcr-catalogs#76]
@yymao  @dkorytov For the ellipticity test, I need to recompute the ellipticity using the axis ratio for the galaxy. (because the data defintion  differs from the schema definition). But I just checked and only have size_minor_bulge_true, size_minor_disk_true, size_true, size_bulge_true, size_disk_true. I need  size_minor_true, which is not available. For protoDC2, this quantity needs to be added (I think Dan was using the r-band luminosity weighted sum of the components ) I can do this by hand for the time being, but the axis ratio needs to be in the schema as well I think.

**Comment by evevkovacs** [comment]
@yymao  @dkorytov @EiffL Actually, we need more quantities. In order to compare with the data, I need to make a cut on morphology. Rachel suggested using B/T cuts, so I also need bulge_to_total ratios as well.

**Comment by yymao** [comment]
`size_minor_true` is already in the [schema](https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/SCHEMA.md). To add it to protoDC2, maybe we should calculate it from `size_true` and `ellipticity_true` so that their relationships remain self-consistent? 

As for bulge to total ratio, is it just `stellar_mass_bulge / stellar_mass`? If so, it seems simple enough that the user can just calculate it on their own?

**Comment by EiffL** [comment]
There are several definitions  out there for  bulge to total ratio, but the one used in Benjamin's COSMOS paper is a ratio of luminosities:
> bulge-to-total ratio of rest-frame K-band luminosity, Rtype = LK,bulge/LK,total, where the K-band closely follows stellar mass over a wide range of redshifts and is ro- bust to uncertainties in modelling details such as reddening. Defining spiral galaxies via Rtype < 0.4, S0 galaxies via 0.4 < Rtype < 0.6, and elliptical galaxies via Rtype > 0.6, the Bower et al. (2006) models yield a distribution of morphologies at low redshift that is consistent with observations.
(Joachimi et al. 2013)
We could easily use something like
```
gc.add_quantity_modifier('morphology/BTR', (lambda x,y : x/(x+y), 'SDSS_filters/spheroidLuminositiesStellar:SDSS_i:observed', 'SDSS_filters/diskLuminositiesStellar:SDSS_i:observed'))
```
just have to pick the right band...

**Comment by EiffL** [comment]
Also, I don't think the luminosity averaged ellipticity is the right thing to use here, we should use the  luminosity averaged moments of  both components to get to the total ellipticity, as in https://github.com/EiffL/DESCUtilities/blob/master/compute_total_ellipticity.ipynb

**Comment by evevkovacs** [comment]
@EiffL Yes, for protoDC2 we can add the quantity as you suggest, but if we want the test to work for other catalogs such as Buzzard, then it would be better for B/T to be exposed in the GCR.  And yes, most observers use luminosity ratios, so I think that's a better measure than the ratios of stellar masses. I agree that luminosity averaged ellipticity is not right and we need to do something more sophisticated in protoDC2 as you suggested. The luminosity weighting was just a quick method to get started. 
@yymao @dkorytov Good idea to use size_true and ellipticity_true, to get size_minor_true. I'll implement that. Sounds like this could also be a consistency check in the readiness test!

**Comment by yymao** [comment]
@EiffL I thought the use of K-band luminosity is due to it's stronger correlation with stellar mass? I'm not sure which optical band we should use to mimic K-band.
