### ISSUE TITLE
Create mask for redmapper-selected galaxies and make it available in GCR

### ISSUE THREAD

**Issue by evevkovacs** [LSSTDESC/gcr-catalogs#81]
Redmapper-selected sample would be useful for many tests. Since the sample is known, we can create and save a mask that could be called in the GCR to make the sample available in DESCQA or for other users by simply applying the mask.

**Comment by yymao** [comment]
@j-dr let me know if you need any help.

**Comment by yymao** [comment]
Closed by #97
